export const dataRequestSchema = {
	_id: '619baf36eb175aaacd592bbb',
	version: 1,
	dataSetId: '',
	publisher: 'ALLIANCE > SAIL',
	formType: '5 safe',
	countOfChanges: 1,
	status: 'draft',
	isCloneable: true,
	guidance: {
		safepeopleprimaryapplicantfullname: 'Guidance for safepeopleprimaryapplicantfullname',
		safepeopleprimaryapplicantjobtitle: 'Guidance for safepeopleprimaryapplicantjobtitle',
		safepeopleprimaryapplicanttelephone: 'Guidance for safepeopleprimaryapplicanttelephone',
	},
	questionSetStatus: {
		'safepeople-primaryapplicant': 1,
		'safepeople-otherindividuals': 0,
	},
	questionStatus: {
		safepeopleprimaryapplicantfullname: 0,
		safepeopleprimaryapplicantjobtitle: 1,
		safepeopleprimaryapplicanttelephone: 0,
		safepeopleprimaryapplicantorcid: 1,
		safepeopleprimaryapplicantemail: 0,
		safepeopleprimaryapplicantaccessdata: 0,
		safepeopleprimaryapplicantaccreditedresearcher: 0,
		safepeopleprimaryapplicanttraininginformationgovernance: 0,
		safepeopleprimaryapplicantorganisationname: 0,
		safepeopleprimaryapplicantorganisationdatasecurityprotectionkit: 0,
		safepeopleprimaryapplicantorganisationdatacontroller: 0,
		safepeopleotherindividualsfullname: 0,
		safepeopleotherindividualsjobtitle: 0,
		safepeopleotherindividualsorganisation: 0,
		safepeopleotherindividualsrole: 0,
		safepeopleotherindividualsaccessdata: 0,
		safepeopleotherindividualsaccreditedresearcher: 0,
		safepeopleotherindividualstraininginformationgovernance: 0,
		safepeopleotherindividualsexperience: 0,
		'add-safepeople-otherindividuals': 0,
		safeprojectaboutthisapplicationtype: 0,
		safeprojectprojectdetailstitle: 0,
		safeprojectprojectdetailstype: 0,
		safeprojectprojectdetailsneworexisting: 0,
		safeprojectprojectdetailslaysummary: 0,
		'safeproject-projectdetails-startdate': 0,
		'safeproject-projectdetails-enddate': 0,
		safeprojectprojectdetailsaimsobjectivesrationale: 0,
		safeprojectprojectdetailsdatausageforobjectives: 0,
		safeprojectprojectdetailspublicbenefitimpact: 0,
		safeprojectprojectdetailspublicpatientinvolvementengagement: 0,
		safeprojectprojectdetailsindividualprivacyriskmitigation: 0,
		safeprojectprojectdetailsgroupindividualdisavantageavoidance: 0,
		safeprojectprojectdetailsresearchprojectsummarykeywords: 0,
		safeprojectprojectdetailsresearchprojectfuturedatabasebenefit: 0,
		safeprojectfunderinformationprojecthasfunder: 0,
		safeprojectsponsorinformationprojecthassponsor: 0,
		safeprojectdeclarationofinteresthascommercialinterest: 0,
		safedatadatafieldsdatarequiredjustification: 0,
		safedatadatafieldsfileuploaded: 0,
		safedatadatafieldsinclusionexclusioncriteria: 0,
		safedatadatafieldsdatarefreshrequired: 0,
		safedataotherdatasetslinkadditionaldatasets: 0,
		safedataotherdatasetsrisksmitigations: 0,
		safedatalawfulbasisgdprarticle6basis: 0,
		safedatalawfulbasisgdprarticle6basisjustification: 0,
		safedatalawfulbasisgdprarticle9conditions: 0,
		safedatalawfulbasisgdprarticle9basisjustification: 0,
		safedataconfidentialityavenuelegalbasisconfidentialinformation: 0,
		safedataethicsapprovalinsightresearch: 0,
		safedataethicsapprovalapprovalobtained: 0,
		safedatastorageandprocessingaccessmethod: 0,
		safedatadataflowdatatransferedoutsideuk: 0,
		safedatadataflowregionsdataprocessed: 0,
		safedatadataflowdetailedinformation: 0,
		safedatadataflowdiagramenclosed: 0,
		safeoutputsoutputsdisseminationplansproposalfindings: 0,
		safeoutputsoutputsdisseminationplansmilestones: 0,
		safeoutputsoutputsdisseminationplansdisclosurecontrolpolicy: 0,
		'safeoutputs-dataretention-retaindatadate': 0,
		safeoutputsdataretentionretaindatadatereason: 0,
		safeoutputsdataretentionretaindataextensionpermissions: 0,
		safeprojectintellectualpropertydevelopmentnewproductprocess: null,
	},
	createdAt: { $date: { $numberLong: '1637592886679' } },
	updatedAt: { $date: { $numberLong: '1637601834397' } },
	__v: 0,
};
