export const expectedSchema = {
	_id: '619baf36eb175aaacd592bbb',
	questionStatus: {
		safepeopleprimaryapplicantfullname: 0,
		safepeopleprimaryapplicantjobtitle: 1,
		safepeopleprimaryapplicanttelephone: 0,
		safepeopleprimaryapplicantorcid: 1,
		safepeopleprimaryapplicantemail: 0,
		safepeopleotherindividualsfullname: 1,
		safepeopleotherindividualsjobtitle: 0,
		safepeopleotherindividualsorganisation: 0,
		safepeopleotherindividualsrole: 0,
		safepeopleotherindividualsaccessdata: 1,
		safepeopleotherindividualsaccreditedresearcher: 0,
		safepeopleotherindividualstraininginformationgovernance: 0,
		safepeopleotherindividualsexperience: 1,
	},
	guidance: {},
	countOfChanges: 0,
};
