### Info
### Description: Rest Client in Visual Studio Code

### Variables
@baseUrl = http://localhost:8000
@apiVersion = v1
@uFirstName = "John"
@uLastName = "Doe"
@uEmail = "john.doe.1234567890@example.com"
@uEmail2 = "john.for.doe.1234567890@example.com"
@uPassword = "passw@rdJ0hnD0e"

### Login
#### create new auth
POST {{baseUrl}}/api/{{apiVersion}}/register HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "firstname": {{uFirstName}},
    "lastname": {{uLastName}},
    "email": {{uEmail}},
    "password": {{uPassword}}
}

### Access Token
# @name loginUsernamePassword
POST {{baseUrl}}/api/{{apiVersion}}/auth HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": {{uEmail}},
    "password": {{uPassword}}
}

### Variables jwt token
@accessToken = {{loginUsernamePassword.response.body.$.access_token}}

### USERS
#### create new user
POST {{baseUrl}}/api/{{apiVersion}}/users HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "firstname": {{uFirstName}},
    "lastname": {{uLastName}},
    "email": {{uEmail2}},
    "password": {{uPassword}}
}

### PERMISSIONS
#### get all permissions
GET {{baseUrl}}/api/{{apiVersion}}/permissions HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

#### get permission by id
GET {{baseUrl}}/api/{{apiVersion}}/permissions/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

#### create new permission
POST {{baseUrl}}/api/{{apiVersion}}/permissions HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "role" : "test"
}

#### update permission by id
PATCH {{baseUrl}}/api/{{apiVersion}}/permissions/6 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "role" : "test2"
}

#### delete permission by id
DELETE {{baseUrl}}/api/{{apiVersion}}/permissions/6 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### USERS
#### get all users
GET {{baseUrl}}/api/{{apiVersion}}/users HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

#### get user by id
GET {{baseUrl}}/api/{{apiVersion}}/users/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

#### create new user
POST {{baseUrl}}/api/{{apiVersion}}/users HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "firstname": "john2",
    "lastname": "doe2",
    "email": "john.doe.test.123456789@test.com",
    "password": "Passw@rd1!"
}

#### update user
PATCH {{baseUrl}}/api/{{apiVersion}}/users/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "firstname": "john23",
    "lastname": "doe2",
    "email": "john.doe2.test.123456789@test.com",
    "password": "Passw@rd1!"
}

#### delete user by id
DELETE {{baseUrl}}/api/{{apiVersion}}/users/12 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### TEAMS
#### get all teams
GET {{baseUrl}}/api/{{apiVersion}}/teams HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

#### get one team by id
GET {{baseUrl}}/api/{{apiVersion}}/teams/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

#### create a new team
POST {{baseUrl}}/api/{{apiVersion}}/teams HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "Test Team Ltd", 
    "enabled": 1,
    "allows_messaging": 1,
    "workflow_enabled": 1,
    "access_requests_management": 1,
    "uses_5_safes": 1,
    "is_admin": 1,
    "member_of": 1001,
    "contact_point": "dinos345@mail.com",
    "application_form_updated_by": "Someone Somewhere",
    "application_form_updated_on": "2023-04-06 15:44:41"
}

#### add new user in team
POST {{baseUrl}}/api/{{apiVersion}}/teams/1/users HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "userId": 1,
    "permissions" : [
        "create",
        "read"
    ]
}

#### update user in team
PUT {{baseUrl}}/api/{{apiVersion}}/teams/1/users/1 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "permissions" : {
        "read": false,
        "create": true,
        "update": true
    }
}

#### update permissions for user in team
DELETE {{baseUrl}}/api/{{apiVersion}}/teams/1/users/2 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}


### Review
#### get all reviews
GET {{baseUrl}}/api/{{apiVersion}}/reviews HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

#### get review by id
GET {{baseUrl}}/api/{{apiVersion}}/reviews/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

#### add new review
POST {{baseUrl}}/api/{{apiVersion}}/reviews HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "tool_id": 1,
    "user_id" : 1,
    "rating" : 4,
    "review_text": "Similique provident natus facere eveniet facere. Cumque corporis et cumque consequatur.",
    "review_state": "active"
}

#### update review
PUT {{baseUrl}}/api/{{apiVersion}}/reviews/11 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "tool_id": 1,
    "user_id" : 1,
    "rating" : 5,
    "review_text": "Similique provident natus facere eveniet facere. Cumque corporis et cumque consequatur.",
    "review_state": "active"
}

#### update review
DELETE {{baseUrl}}/api/{{apiVersion}}/reviews/11 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

### Collections 
#### get all collections
GET {{baseUrl}}/api/{{apiVersion}}/collections HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

#### get collection by id
GET {{baseUrl}}/api/{{apiVersion}}/collections/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

#### add new collection
POST {{baseUrl}}/api/{{apiVersion}}/collections HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "covid",
    "description" : "Dolorem voluptas consequatur nihil illum et sunt libero.",
    "image_link" : "https://via.placeholder.com/640x480.png/0022bb?text=animals+cumque",
    "enabled": true,
    "keywords": "key words",
    "public": true,
    "counter": 123
}

#### update collection
PUT {{baseUrl}}/api/{{apiVersion}}/collections/12 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "covid 2",
    "description" : "Dolorem voluptas consequatur nihil illum et sunt libero.",
    "image_link" : "https://via.placeholder.com/640x480.png/0022bb?text=animals+cumque",
    "enabled": true,
    "keywords": "key words",
    "public": true,
    "counter": 123
}

#### delete collection
DELETE {{baseUrl}}/api/{{apiVersion}}/collections/11 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}


### Exceptions
#### test validation
POST {{baseUrl}}/api/{{apiVersion}}/test-validation HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "covid",
}

#### test exception
POST {{baseUrl}}/api/{{apiVersion}}/test-exception HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "covid",
}
