export const dataUseRegisterUploads = [
	{
		projectTitle: 'This a test data use register',
		projectIdText: 'this is the project id',
		datasetNames: [
			'This is the dataset title',
			'http://localhost:3000/dataset/f725187f-7352-482b-a43b-64ebc96e66f2',
			'http://localhost:3000/dataset/c6d6bbd3-74ed-46af-841d-ac5e05f4da41',
			'http://localhost:3000/dataset/e55df485-5acd-4606-bbb8-668d4c06380a',
		],
		applicantNames: [' Michael Donnelly', 'http://localhost:3000/person/8495781222000176', 'http://localhost:3000/person/4495285946631793'],
		organisationName: 'organisation name',
		organisationSector: 'organisation sector',
		applicantId: 'applicant id',
		fundersAndSponsors: 'funder1 , funder2 , funder3 ',
		accreditedResearcherStatus: 'accredited Researcher Status',
		sublicenceArrangements: 'sublicence Arrangements',
		laySummary: 'lay Summary',
		publicBenefitStatement: 'public Benefit Statement',
		requestCategoryType: 'request Category Type',
		technicalSummary: 'technical Summary',
		otherApprovalCommittees: 'other Approval Committees',
		projectStartDate: '2021-09-25',
		projectEndDate: '2021-09-30',
		latestApprovalDate: '2021-09-21',
		dataSensitivityLevel: 'data Sensitivity Level',
		legalBasisForDataArticle6: 'legal Basis For Data 6',
		legalBasisForDataArticle9: 'legal Basis For Data 9',
		dutyOfConfidentiality: 'duty Of Confidentiality',
		nationalDataOptOut: 'national Data Opt Out',
		requestFrequency: 'request Frequency',
		datasetLinkageDescription: 'data Processing Description',
		confidentialDataDescription: 'confidential Data Description',
		accessDate: '2021-09-26',
		accessType: 'accessType',
		privacyEnhancements: 'privacy Enhancements',
		researchOutputs: 'research Outputs',
		relatedObjects: [],
	},
	{
		projectTitle: 'This is another test data use register',
		projectIdText: 'this is the other project id',
		datasetNames: [
			'This is the dataset title',
			'http://localhost:3000/dataset/f725187f-7352-482b-a43b-64ebc96e66f2',
			'http://localhost:3000/dataset/c6d6bbd3-74ed-46af-841d-ac5e05f4da41',
			'http://localhost:3000/dataset/e55df485-5acd-4606-bbb8-668d4c06380a',
		],
		applicantNames: [' Michael Donnelly', 'http://localhost:3000/person/8495781222000176', 'http://localhost:3000/person/4495285946631793'],
		organisationName: 'organisation name',
		organisationSector: 'organisation sector',
		applicantId: 'applicant id',
		fundersAndSponsors: 'funder1 , funder2 , funder3 ',
		accreditedResearcherStatus: 'accredited Researcher Status',
		sublicenceArrangements: 'sublicence Arrangements',
		laySummary: 'other lay Summary',
		publicBenefitStatement: 'public Benefit Statement',
		requestCategoryType: 'request Category Type',
		technicalSummary: 'technical Summary',
		otherApprovalCommittees: 'other Approval Committees',
		projectStartDate: '2021-09-25',
		projectEndDate: '2021-09-30',
		latestApprovalDate: '2021-09-21',
		dataSensitivityLevel: 'data Sensitivity Level',
		legalBasisForDataArticle6: 'legal Basis For Data 6',
		legalBasisForDataArticle9: 'legal Basis For Data 9',
		dutyOfConfidentiality: 'duty Of Confidentiality',
		nationalDataOptOut: 'national Data Opt Out',
		requestFrequency: 'request Frequency',
		datasetLinkageDescription: 'data Processing Description',
		confidentialDataDescription: 'confidential Data Description',
		accessDate: '2021-09-26',
		accessType: 'accessType',
		privacyEnhancements: 'privacy Enhancements',
		researchOutputs: 'research Outputs',
	},
];

export const dataUseRegisterUploadsWithDuplicates = [
	{
		projectTitle: 'This a test data use register',
		projectIdText: 'this is the project id',
		datasetNames: [
			'This is the dataset title',
			'http://localhost:3000/dataset/f725187f-7352-482b-a43b-64ebc96e66f2',
			'http://localhost:3000/dataset/c6d6bbd3-74ed-46af-841d-ac5e05f4da41',
			'http://localhost:3000/dataset/e55df485-5acd-4606-bbb8-668d4c06380a',
		],
		applicantNames: [' Michael Donnelly', 'http://localhost:3000/person/8495781222000176', 'http://localhost:3000/person/4495285946631793'],
		organisationName: 'organisation name',
		organisationSector: 'organisation sector',
		applicantId: 'applicant id',
		fundersAndSponsors: 'funder1 , funder2 , funder3 ',
		accreditedResearcherStatus: 'accredited Researcher Status',
		sublicenceArrangements: 'sublicence Arrangements',
		laySummary: 'lay Summary',
		publicBenefitStatement: 'public Benefit Statement',
		requestCategoryType: 'request Category Type',
		technicalSummary: 'technical Summary',
		otherApprovalCommittees: 'other Approval Committees',
		projectStartDate: '2021-09-25',
		projectEndDate: '2021-09-30',
		latestApprovalDate: '2021-09-21',
		dataSensitivityLevel: 'data Sensitivity Level',
		legalBasisForDataArticle6: 'legal Basis For Data 6',
		legalBasisForDataArticle9: 'legal Basis For Data 9',
		dutyOfConfidentiality: 'duty Of Confidentiality',
		nationalDataOptOut: 'national Data Opt Out',
		requestFrequency: 'request Frequency',
		datasetLinkageDescription: 'data Processing Description',
		confidentialDataDescription: 'confidential Data Description',
		accessDate: '2021-09-26',
		accessType: 'accessType',
		privacyEnhancements: 'privacy Enhancements',
		researchOutputs: 'research Outputs',
	},
	{
		projectTitle: 'This a test data use register',
		projectIdText: 'this is the project id',
		datasetNames: [
			'This is the dataset title',
			'http://localhost:3000/dataset/f725187f-7352-482b-a43b-64ebc96e66f2',
			'http://localhost:3000/dataset/c6d6bbd3-74ed-46af-841d-ac5e05f4da41',
			'http://localhost:3000/dataset/e55df485-5acd-4606-bbb8-668d4c06380a',
		],
		applicantNames: [' Michael Donnelly', 'http://localhost:3000/person/8495781222000176', 'http://localhost:3000/person/4495285946631793'],
		organisationName: 'organisation name',
		organisationSector: 'organisation sector',
		applicantId: 'applicant id',
		fundersAndSponsors: 'funder1 , funder2 , funder3 ',
		accreditedResearcherStatus: 'accredited Researcher Status',
		sublicenceArrangements: 'sublicence Arrangements',
		laySummary: 'lay Summary',
		publicBenefitStatement: 'public Benefit Statement',
		requestCategoryType: 'request Category Type',
		technicalSummary: 'technical Summary',
		otherApprovalCommittees: 'other Approval Committees',
		projectStartDate: '2021-09-25',
		projectEndDate: '2021-09-30',
		latestApprovalDate: '2021-09-21',
		dataSensitivityLevel: 'data Sensitivity Level',
		legalBasisForDataArticle6: 'legal Basis For Data 6',
		legalBasisForDataArticle9: 'legal Basis For Data 9',
		dutyOfConfidentiality: 'duty Of Confidentiality',
		nationalDataOptOut: 'national Data Opt Out',
		requestFrequency: 'request Frequency',
		datasetLinkageDescription: 'data Processing Description',
		confidentialDataDescription: 'confidential Data Description',
		accessDate: '2021-09-26',
		accessType: 'accessType',
		privacyEnhancements: 'privacy Enhancements',
		researchOutputs: 'research Outputs',
	},
	{
		projectTitle: 'This a test data use register',
		projectIdText: 'this is the project id',
		datasetNames: [
			'This is the dataset title',
			'http://localhost:3000/dataset/f725187f-7352-482b-a43b-64ebc96e66f2',
			'http://localhost:3000/dataset/c6d6bbd3-74ed-46af-841d-ac5e05f4da41',
			'http://localhost:3000/dataset/e55df485-5acd-4606-bbb8-668d4c06380a',
		],
		applicantNames: [' Michael Donnelly', 'http://localhost:3000/person/8495781222000176', 'http://localhost:3000/person/4495285946631793'],
		organisationName: 'organisation name',
		organisationSector: 'organisation sector',
		applicantId: 'applicant id',
		fundersAndSponsors: 'funder1 , funder2 , funder3 ',
		accreditedResearcherStatus: 'accredited Researcher Status',
		sublicenceArrangements: 'sublicence Arrangements',
		laySummary: 'lay Summary',
		publicBenefitStatement: 'public Benefit Statement',
		requestCategoryType: 'request Category Type',
		technicalSummary: 'technical Summary',
		otherApprovalCommittees: 'other Approval Committees',
		projectStartDate: '2021-09-25',
		projectEndDate: '2021-09-30',
		latestApprovalDate: '2021-09-21',
		dataSensitivityLevel: 'data Sensitivity Level',
		legalBasisForDataArticle6: 'legal Basis For Data 6',
		legalBasisForDataArticle9: 'legal Basis For Data 9',
		dutyOfConfidentiality: 'duty Of Confidentiality',
		nationalDataOptOut: 'national Data Opt Out',
		requestFrequency: 'request Frequency',
		datasetLinkageDescription: 'data Processing Description',
		confidentialDataDescription: 'confidential Data Description',
		accessDate: '2021-09-26',
		accessType: 'accessType',
		privacyEnhancements: 'privacy Enhancements',
		researchOutputs: 'research Outputs',
	},
	{
		projectTitle: 'This a test data use register',
		projectIdText: 'this is the project id',
		datasetNames: [
			'This is the dataset title',
			'http://localhost:3000/dataset/f725187f-7352-482b-a43b-64ebc96e66f2',
			'http://localhost:3000/dataset/c6d6bbd3-74ed-46af-841d-ac5e05f4da41',
			'http://localhost:3000/dataset/e55df485-5acd-4606-bbb8-668d4c06380a',
		],
		applicantNames: [' Michael Donnelly', 'http://localhost:3000/person/8495781222000176', 'http://localhost:3000/person/4495285946631793'],
		organisationName: 'organisation name',
		organisationSector: 'organisation sector',
		applicantId: 'applicant id',
		fundersAndSponsors: 'funder1 , funder2 , funder3 ',
		accreditedResearcherStatus: 'accredited Researcher Status',
		sublicenceArrangements: 'sublicence Arrangements',
		laySummary: 'lay Summary',
		publicBenefitStatement: 'public Benefit Statement',
		requestCategoryType: 'request Category Type',
		technicalSummary: 'technical Summary',
		otherApprovalCommittees: 'other Approval Committees',
		projectStartDate: '2021-09-25',
		projectEndDate: '2021-09-30',
		latestApprovalDate: '2021-09-21',
		dataSensitivityLevel: 'data Sensitivity Level',
		legalBasisForDataArticle6: 'legal Basis For Data 6',
		legalBasisForDataArticle9: 'legal Basis For Data 9',
		dutyOfConfidentiality: 'duty Of Confidentiality',
		nationalDataOptOut: 'national Data Opt Out',
		requestFrequency: 'request Frequency',
		datasetLinkageDescription: 'data Processing Description',
		confidentialDataDescription: 'confidential Data Description',
		accessDate: '2021-09-26',
		accessType: 'accessType',
		privacyEnhancements: 'privacy Enhancements',
		researchOutputs: 'research Outputs',
	},
	{
		projectTitle: 'This a test data use register',
		projectIdText: 'this is another project id',
		datasetNames: [
			'This is the dataset title',
			'http://localhost:3000/dataset/f725187f-7352-482b-a43b-64ebc96e66f2',
			'http://localhost:3000/dataset/c6d6bbd3-74ed-46af-841d-ac5e05f4da41',
			'http://localhost:3000/dataset/e55df485-5acd-4606-bbb8-668d4c06380a',
		],
		applicantNames: [' Michael Donnelly', 'http://localhost:3000/person/8495781222000176', 'http://localhost:3000/person/4495285946631793'],
		organisationName: 'another organisation name',
		organisationSector: 'organisation sector',
		applicantId: 'applicant id',
		fundersAndSponsors: 'funder1 , funder2 , funder3 ',
		accreditedResearcherStatus: 'accredited Researcher Status',
		sublicenceArrangements: 'sublicence Arrangements',
		laySummary: 'lay Summary',
		publicBenefitStatement: 'public Benefit Statement',
		requestCategoryType: 'request Category Type',
		technicalSummary: 'technical Summary',
		otherApprovalCommittees: 'other Approval Committees',
		projectStartDate: '2021-09-25',
		projectEndDate: '2021-09-30',
		latestApprovalDate: '2021-09-21',
		dataSensitivityLevel: 'data Sensitivity Level',
		legalBasisForDataArticle6: 'legal Basis For Data 6',
		legalBasisForDataArticle9: 'legal Basis For Data 9',
		dutyOfConfidentiality: 'duty Of Confidentiality',
		nationalDataOptOut: 'national Data Opt Out',
		requestFrequency: 'request Frequency',
		datasetLinkageDescription: 'data Processing Description',
		confidentialDataDescription: 'confidential Data Description',
		accessDate: '2021-09-26',
		accessType: 'accessType',
		privacyEnhancements: 'privacy Enhancements',
		researchOutputs: 'research Outputs',
	},
	{
		projectTitle: 'This a test data use register',
		projectIdText: 'this is another project id',
		datasetNames: [
			'This is the dataset title',
			'http://localhost:3000/dataset/f725187f-7352-482b-a43b-64ebc96e66f2',
			'http://localhost:3000/dataset/c6d6bbd3-74ed-46af-841d-ac5e05f4da41',
			'http://localhost:3000/dataset/e55df485-5acd-4606-bbb8-668d4c06380a',
		],
		applicantNames: [' Michael Donnelly', 'http://localhost:3000/person/8495781222000176', 'http://localhost:3000/person/4495285946631793'],
		organisationName: 'another organisation name',
		organisationSector: 'organisation sector',
		applicantId: 'applicant id',
		fundersAndSponsors: 'funder1 , funder2 , funder3 ',
		accreditedResearcherStatus: 'accredited Researcher Status',
		sublicenceArrangements: 'sublicence Arrangements',
		laySummary: 'another lay Summary',
		publicBenefitStatement: 'public Benefit Statement',
		requestCategoryType: 'request Category Type',
		technicalSummary: 'technical Summary',
		otherApprovalCommittees: 'other Approval Committees',
		projectStartDate: '2021-09-25',
		projectEndDate: '2021-09-30',
		latestApprovalDate: '2021-09-21',
		dataSensitivityLevel: 'data Sensitivity Level',
		legalBasisForDataArticle6: 'legal Basis For Data 6',
		legalBasisForDataArticle9: 'legal Basis For Data 9',
		dutyOfConfidentiality: 'duty Of Confidentiality',
		nationalDataOptOut: 'national Data Opt Out',
		requestFrequency: 'request Frequency',
		datasetLinkageDescription: 'data Processing Description',
		confidentialDataDescription: 'confidential Data Description',
		accessDate: '2021-09-26',
		accessType: 'accessType',
		privacyEnhancements: 'privacy Enhancements',
		researchOutputs: 'research Outputs',
	},
];

export const datasets = [
	{
		id: '70b4d407-288a-4945-a4d5-506d60715110',
		pid: 'e55df485-5acd-4606-bbb8-668d4c06380a',
	},
	{
		id: '82ef7d1a-98d8-48b6-9acd-461bf2a399c3',
		pid: 'e55df485-5acd-4606-bbb8-668d4c06380a',
	},
	{
		id: '673626f3-bdac-4d32-9bb8-c890b727c0d1',
		pid: '594d79a4-92b9-4a7f-b991-abf850bf2b67',
	},
	{
		id: '89e57932-ac48-48ac-a6e5-29795bc38b94',
		pid: 'efbd4275-70e2-4887-8499-18b1fb24ce5b',
	},
];

export const relatedObjectDatasets = [
	{
		objectId: '70b4d407-288a-4945-a4d5-506d60715110',
		pid: 'e55df485-5acd-4606-bbb8-668d4c06380a',
		objectType: 'dataset',
		user: 'James Smith',
		updated: '24 Sept 2021',
		isLocked: true,
		reason: 'This dataset was added automatically during the manual upload of this data use register',
	},
	{
		objectId: '82ef7d1a-98d8-48b6-9acd-461bf2a399c3',
		pid: 'e55df485-5acd-4606-bbb8-668d4c06380a',
		objectType: 'dataset',
		user: 'James Smith',
		updated: '24 Sept 2021',
		isLocked: true,
		reason: 'This dataset was added automatically during the manual upload of this data use register',
	},
	{
		objectId: '673626f3-bdac-4d32-9bb8-c890b727c0d1',
		pid: '594d79a4-92b9-4a7f-b991-abf850bf2b67',
		objectType: 'dataset',
		user: 'James Smith',
		updated: '24 Sept 2021',
		isLocked: true,
		reason: 'This dataset was added automatically during the manual upload of this data use register',
	},
	{
		objectId: '89e57932-ac48-48ac-a6e5-29795bc38b94',
		pid: 'efbd4275-70e2-4887-8499-18b1fb24ce5b',
		objectType: 'dataset',
		user: 'James Smith',
		updated: '24 Sept 2021',
		isLocked: true,
		reason: 'This dataset was added automatically during the manual upload of this data use register',
	},
];

export const nonGatewayDatasetNames = ['dataset one', 'dataset two', ' dataset three', 'dataset four'];

export const gatewayDatasetNames = [
	'http://localhost:3000/dataset/f725187f-7352-482b-a43b-64ebc96e66f2',
	'http://localhost:3000/dataset/c6d6bbd3-74ed-46af-841d-ac5e05f4da41',
	'http://localhost:3000/dataset/e55df485-5acd-4606-bbb8-668d4c06380a',
];

export const expectedGatewayDatasets = [
	{ datasetid: '1', name: 'dataset 1', pid: '111' },
	{ datasetid: '2', name: 'dataset 2', pid: '222' },
	{ datasetid: '3', name: 'dataset 3', pid: '333' },
];

export const expectedGatewayDatasetsReturned = [
	{ id: '1', name: 'dataset 1', pid: '111' },
	{ id: '2', name: 'dataset 2', pid: '222' },
	{ id: '3', name: 'dataset 3', pid: '333' },
];

export const nonGatewayApplicantNames = ['applicant one', 'applicant two', 'applicant three', 'applicant four'];

export const gatewayApplicantNames = ['http://localhost:3000/person/8495781222000176', 'http://localhost:3000/person/4495285946631793'];

export const expectedGatewayApplicants = ['89e57932-ac48-48ac-a6e5-29795bc38b94', '0cfe60cd-038d-4c03-9a95-894c52135922'];

export const applications = [
	{
		questionAnswers: {
			safepeopleprimaryapplicantfullname: 'applicant name',
			safeprojectfunderinformationprojecthasfundername: 'funder 1',
			safeprojectfunderinformationprojecthasfundername_gRvcG: 'funder 2',
			safeprojectsponsorinformationprojecthassponsororganisationname: 'sponsor 1',
			safeprojectsponsorinformationprojecthassponsororganisationname_2gixm: 'sponsor 2',
			safepeopleprimaryapplicantfullname: 'James Smith',
			safepeopleprimaryapplicantfullname_xRtvc: 'Michael Howard',
			safepeopleotherindividualsfullname: 'Colin Devlin',
			safepeopleotherindividualsfullname_3uGds: 'Graham Patterson',
		},
	},
];

export const authors = [
	{ _id: '607db9c6e1f9d3704d570d93', firstname: 'James', lastname: 'Smith' },
	{ _id: '5fb628de6f3f9767bd2d9281', firstname: 'Michael', lastname: 'Howard' },
];

export const editedDataUseObject = {
	projectTitle: 'This a test data use register with an edited title',
	projectIdText: 'this is the project id',
	datasetNames: [
		'This is the dataset title',
		'http://localhost:3000/dataset/f725187f-7352-482b-a43b-64ebc96e66f2',
		'http://localhost:3000/dataset/c6d6bbd3-74ed-46af-841d-ac5e05f4da41',
		'http://localhost:3000/dataset/e55df485-5acd-4606-bbb8-668d4c06380a',
	],
	applicantNames: [' Michael Donnelly', 'http://localhost:3000/person/8495781222000176', 'http://localhost:3000/person/4495285946631793'],
	organisationName: 'organisation name',
	organisationSector: 'organisation sector',
	applicantId: 'applicant id',
	fundersAndSponsors: 'funder1 , funder2 , funder3 ',
	accreditedResearcherStatus: 'accredited Researcher Status',
	sublicenceArrangements: 'sublicence Arrangements',
	laySummary: 'lay Summary',
	publicBenefitStatement: 'public Benefit Statement',
	requestCategoryType: 'request Category Type',
	technicalSummary: 'technical Summary',
	otherApprovalCommittees: 'other Approval Committees',
	projectStartDate: '2021-09-25',
	projectEndDate: '2021-09-30',
	latestApprovalDate: '2021-09-21',
	dataSensitivityLevel: 'data Sensitivity Level',
	legalBasisForDataArticle6: 'legal Basis For Data 6',
	legalBasisForDataArticle9: 'legal Basis For Data 9',
	dutyOfConfidentiality: 'duty Of Confidentiality',
	nationalDataOptOut: 'national Data Opt Out',
	requestFrequency: 'request Frequency',
	datasetLinkageDescription: 'data Processing Description',
	confidentialDataDescription: 'confidential Data Description',
	accessDate: '2021-09-26',
	accessType: 'accessType',
	privacyEnhancements: 'privacy Enhancements',
	researchOutputs: 'research Outputs',
	relatedObjects: [],
};

export const dataUseRegistersStub = [
	{
		_id: 'test_id',
		counter: 1,
		keywords: ['Blood', 'Test'],
		datasetTitles: ['HDR UK Papers & Preprints'],
		gatewayDatasets: ['1ccb9da3-4b5e-4b4b-a142-af739037983c'],
		nonGatewayDatasets: [],
		gatewayApplicants: [],
		nonGatewayApplicants: ['John Smith'],
		fundersAndSponsors: [],
		otherApprovalCommittees: [],
		gatewayOutputsTools: [514564326145692],
		gatewayOutputsPapers: [7485531672584456],
		nonGatewayOutputs: ['www.yahoo.com'],
		publisher: 'testPub',
		projectIdText: '619B-73C4-BCB0-7C22-D168-4DAC',
		projectId: 'testId',
		applicantId: '',
		accreditedResearcherStatus: 'Unknown',
		projectTitle: 'This is the title for Pauls Project',
		organisationName: 'PA Consulting',
		laySummary: 'This is the lay summary for Pauls Project',
		publicBenefitStatement: 'This is how my project benefit the public and what is the anticipated impact',
		dutyOfConfidentiality: 'Informed consent',
		datasetLinkageDescription: '',
		requestFrequency: 'One-off',
		legalBasisForDataArticle6:
			'(e) processing is necessary for the performance of a task carried out in the public interest or in the exercise of official authority vested in the controller;',
		legalBasisForDataArticle9:
			'(c) processing is necessary to protect the vital interests of the data subject or of another natural person where the data subject is physically or legally incapable of giving consent;',
		privacyEnhancements: 'These are the steps',
		latestApprovalDate: '2021-11-22T11:04:03.288Z',
		relatedObjects: [],
		activeflag: 'active',
		user: 'userId',
		userName: 'Paul McCafferty',
		updatedon: '2021-12-17T10:54:39.812Z',
		lastActivity: '2021-12-17T10:54:39.812Z',
		manualUpload: false,
		id: 17931311209279556,
		type: 'dataUseRegister',
		createdAt: '2021-11-22T11:04:03.507Z',
		updatedAt: '2021-12-17T10:54:39.815Z',
		__v: 0,
		accessType: 'Release',
	},
	{
		_id: 'test_id2',
		counter: 1,
		keywords: ['Blood', 'Test'],
		datasetTitles: ['HDR UK Papers & Preprints'],
		gatewayDatasets: ['1ccb9da3-4b5e-4b4b-a142-af739037983c'],
		nonGatewayDatasets: [],
		gatewayApplicants: [],
		nonGatewayApplicants: ['John Smith'],
		fundersAndSponsors: [],
		otherApprovalCommittees: [],
		gatewayOutputsTools: [514564326145692],
		gatewayOutputsPapers: [7485531672584456],
		nonGatewayOutputs: ['www.yahoo.com'],
		publisher: 'testPub',
		projectIdText: '619B-73C4-BCB0-7C22-D168-4DAC',
		projectId: 'testId2',
		applicantId: '',
		accreditedResearcherStatus: 'Unknown',
		projectTitle: 'This is the title for Pauls Second Project',
		organisationName: 'PA Consulting',
		laySummary: 'This is the lay summary for Pauls Second Project',
		publicBenefitStatement: 'This is how my project benefit the public and what is the anticipated impact',
		dutyOfConfidentiality: 'Informed consent',
		datasetLinkageDescription: '',
		requestFrequency: 'One-off',
		legalBasisForDataArticle6:
			'(e) processing is necessary for the performance of a task carried out in the public interest or in the exercise of official authority vested in the controller;',
		legalBasisForDataArticle9:
			'(c) processing is necessary to protect the vital interests of the data subject or of another natural person where the data subject is physically or legally incapable of giving consent;',
		privacyEnhancements: 'These are the steps',
		latestApprovalDate: '2021-11-22T11:04:03.288Z',
		relatedObjects: [],
		activeflag: 'active',
		user: 'userId',
		userName: 'Paul McCafferty',
		updatedon: '2021-12-17T10:54:39.812Z',
		lastActivity: '2021-12-17T10:54:39.812Z',
		manualUpload: false,
		id: 17931311209279556,
		type: 'dataUseRegister',
		createdAt: '2021-11-22T11:04:03.507Z',
		updatedAt: '2021-12-17T10:54:39.815Z',
		__v: 0,
		accessType: 'Release',
	},
];
