export const datasetFilters = [
	{
		id: 1,
		label: 'Publisher',
		key: 'publisher',
		tooltip: null,
		closed: true,
		isSearchable: false,
		selectedCount: 0,
		filters: [],
		highlighted: [],
	},
	{
		id: 2,
		label: 'Keywords',
		key: 'keywords',
		tooltip: null,
		closed: true,
		isSearchable: false,
		selectedCount: 0,
		filters: [],
		highlighted: [],
	},
	{
		id: 3,
		label: 'Phenotype',
		key: 'phenotype',
		tooltip: null,
		closed: true,
		isSearchable: false,
		selectedCount: 0,
		filters: [],
		highlighted: [],
	},
	{
		id: 4,
		label: 'Coverage',
		key: 'coverage',
		tooltip: 'The geographical area covered by the dataset.',
		closed: true,
		isSearchable: false,
		selectedCount: 0,
		filters: [
			{
				id: 5,
				label: 'Spatial',
				key: 'spatial',
				tooltip: null,
				closed: true,
				isSearchable: false,
				selectedCount: 0,
				filters: [],
				highlighted: [],
			},
			{
				id: 6,
				label: 'Physical sample availability',
				key: 'physicalSampleAvailability',
				tooltip: null,
				closed: true,
				isSearchable: false,
				selectedCount: 0,
				filters: [],
				highlighted: [],
			},
			{
				id: 7,
				label: 'Follow up',
				key: 'followup',
				tooltip: 'The typical time span that a patient appears in the dataset',
				closed: true,
				isSearchable: false,
				selectedCount: 0,
				filters: [],
				highlighted: [],
			},
		],
	},
	{
		id: 8,
		label: 'Provenance',
		key: 'provenance',
		tooltip: null,
		closed: true,
		isSearchable: false,
		selectedCount: 0,
		filters: [
			{
				id: 9,
				label: 'Purpose',
				key: 'purpose',
				tooltip: null,
				closed: true,
				isSearchable: false,
				selectedCount: 0,
				filters: [],
				highlighted: [],
			},
			{
				id: 10,
				label: 'Source',
				key: 'source',
				tooltip: null,
				closed: true,
				isSearchable: false,
				selectedCount: 0,
				filters: [],
				highlighted: [],
			},
			{
				id: 11,
				label: 'Collection situation',
				key: 'collectionSituation',
				tooltip: null,
				closed: true,
				isSearchable: false,
				selectedCount: 0,
				filters: [],
				highlighted: [],
			},
			{
				id: 12,
				label: 'Accrual periodicity',
				key: 'accrualPeriodicity',
				tooltip: 'The frequency of publishing.',
				closed: true,
				isSearchable: false,
				selectedCount: 0,
				filters: [],
				highlighted: [],
			},
			{
				id: 13,
				label: 'Time lag ',
				key: 'timeLag',
				tooltip: 'The typical time-lag between an event and the data for that event appearing in the dataset.',
				closed: true,
				isSearchable: false,
				selectedCount: 0,
				filters: [],
				highlighted: [],
			},
		],
	},
	{
		id: 14,
		label: 'Access',
		key: 'access',
		tooltip: null,
		closed: true,
		isSearchable: false,
		selectedCount: 0,
		filters: [
			{
				id: 15,
				label: 'Delivery lead time',
				key: 'deliveryLeadTime',
				tooltip: 'Please provide an indication of the typical processing times based on the types of requests typically received.',
				closed: true,
				isSearchable: false,
				selectedCount: 0,
				filters: [],
				highlighted: [],
			},
			{
				id: 16,
				label: 'Jurisdiction',
				key: 'jurisdiction',
				tooltip:
					'Select the country/state under whose laws the data subjects’ data is collected, processed and stored. Select all that apply.',
				closed: true,
				isSearchable: false,
				selectedCount: 0,
				filters: [],
				highlighted: [],
			},
		],
	},
	{
		id: 17,
		label: 'Format and standards',
		key: 'formatAndStandards',
		tooltip: null,
		closed: true,
		isSearchable: false,
		selectedCount: 0,
		filters: [
			{
				id: 18,
				label: 'Vocabulary encoding scheme',
				key: 'vocabularyEncodingScheme',
				tooltip: 'Terminologies, ontologies and controlled vocabularies being used by the dataset.',
				closed: true,
				isSearchable: false,
				selectedCount: 0,
				filters: [],
				highlighted: [],
			},
			{
				id: 19,
				label: 'Conforms to',
				key: 'conformsTo',
				tooltip: 'Standardised data models that the dataset has been stored in or transformed to.',
				closed: true,
				isSearchable: false,
				selectedCount: 0,
				filters: [],
				highlighted: [],
			},
			{
				id: 20,
				label: 'Language',
				key: 'language',
				tooltip: 'Standardised data models that the dataset has been stored in or transformed to.',
				closed: true,
				isSearchable: false,
				selectedCount: 0,
				filters: [],
				highlighted: [],
			},
		],
	},
	{
		id: 21,
		label: 'Data utility',
		key: 'dataUtility',
		tooltip: null,
		closed: true,
		isSearchable: false,
		selectedCount: 0,
		filters: [
			{
				id: 22,
				label: 'Documentation',
				key: 'documentation',
				tooltip: null,
				closed: true,
				isSearchable: false,
				selectedCount: 0,
				filters: [
					{
						id: 23,
						label: 'Additional documentation and support',
						key: 'availability_of_additional_documentation_and_support',
						tooltip: 'Available dataset documentation in addition to the data dictionary.',
						closed: true,
						isSearchable: false,
						selectedCount: 0,
						filters: [],
						highlighted: [],
					},
					{
						id: 24,
						label: 'Data model',
						key: 'data_model',
						tooltip: 'Availability of clear, documented data model.',
						closed: true,
						isSearchable: false,
						selectedCount: 0,
						filters: [],
						highlighted: [],
					},
					{
						id: 25,
						label: 'Data dictionary',
						key: 'data_dictionary',
						tooltip: 'Provided documented data dictionary and terminologies.',
						closed: true,
						isSearchable: false,
						selectedCount: 0,
						filters: [],
						highlighted: [],
					},
					{
						id: 26,
						label: 'Provenance',
						key: 'provenance',
						tooltip: 'Clear descriptions of source and history of the dataset, providing a ‘transparent data pipeline’.',
						closed: true,
						isSearchable: false,
						selectedCount: 0,
						filters: [],
						highlighted: [],
					},
				],
			},
			{
				id: 27,
				label: 'Technical quality',
				key: 'technicalQuality',
				tooltip: null,
				closed: true,
				isSearchable: false,
				selectedCount: 0,
				filters: [
					{
						id: 28,
						label: 'Data Quality Management Process',
						key: 'data_quality_management_process',
						tooltip: 'Available dataset documentation in addition to the data dictionary.',
						closed: true,
						isSearchable: false,
						selectedCount: 0,
						filters: [],
						highlighted: [],
					},
				],
			},
			{
				id: 29,
				label: 'Access and provision ',
				key: 'accessAndProvision ',
				tooltip: null,
				closed: true,
				isSearchable: false,
				selectedCount: 0,
				filters: [
					{
						id: 30,
						label: 'Allowable uses',
						key: 'allowable_uses',
						tooltip: 'Allowable dataset usages as per the licencing agreement.',
						closed: true,
						isSearchable: false,
						selectedCount: 0,
						filters: [],
						highlighted: [],
					},
					{
						id: 31,
						label: 'Time lag',
						key: 'time_lag',
						tooltip: 'Lag between the data being collected and added to the dataset.',
						closed: true,
						isSearchable: false,
						selectedCount: 0,
						filters: [
							{ id: 146, label: 'Alaska', value: 'Alaska', checked: false },
							{ id: 147, label: 'Belgium', value: 'Belgium', checked: false },
						],
						highlighted: [],
					},
					{
						id: 32,
						label: 'Timeliness',
						key: 'timeliness',
						tooltip: 'Average data access request timeframe.',
						closed: true,
						isSearchable: false,
						selectedCount: 0,
						filters: [],
						highlighted: [],
					},
				],
			},
			{
				id: 33,
				label: 'Value and interest',
				key: 'valueAndInterest ',
				tooltip: null,
				closed: true,
				isSearchable: false,
				selectedCount: 0,
				filters: [
					{
						id: 34,
						label: 'Linkages',
						key: 'linkages',
						tooltip: 'Ability to link with other datasets.',
						closed: true,
						isSearchable: false,
						selectedCount: 0,
						filters: [],
						highlighted: [],
					},
					{
						id: 35,
						label: 'Data Enrichments',
						key: 'data_enrichments',
						tooltip: 'Data sources enriched with annotations, image labels, phenomes, derivations, NLP derived data labels.',
						closed: true,
						isSearchable: false,
						selectedCount: 0,
						filters: [],
						highlighted: [],
					},
				],
			},
			{
				id: 36,
				label: 'Coverage',
				key: 'coverage ',
				tooltip: null,
				closed: true,
				isSearchable: false,
				selectedCount: 0,
				filters: [
					{
						id: 37,
						label: 'Pathway coverage',
						key: 'pathway_coverage',
						tooltip: 'Representation of multi-disciplinary healthcare data.',
						closed: true,
						isSearchable: false,
						selectedCount: 0,
						filters: [],
						highlighted: [],
					},
					{
						id: 38,
						label: 'Length of follow up',
						key: 'length_of_follow_up',
						tooltip: 'Data sources enriched with annotations, image labels, phenomes, derivations, NLP derived data labels.',
						closed: true,
						isSearchable: false,
						selectedCount: 0,
						filters: [],
						highlighted: [],
					},
				],
			},
		],
	},
	{
		id: 39,
		label: 'Technical Metadata',
		key: 'technicalMetadata',
		tooltip: null,
		closed: true,
		isSearchable: false,
		selectedCount: 0,
		filters: [],
	},
];
