apiVersion: v1
kind: Service
metadata:
  name: gateway-api
  labels:
    app: gateway-api
spec:
  ports:
    - port: 8000
      protocol: "TCP"
      targetPort: 8000
      # nodePort: 8000
  selector:
    app: gateway-api
