apiVersion: v1
kind: Service
metadata:
  name: gateway-api
  namespace: default
  labels:
    app: gateway-api
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 8000
      targetPort: 8000
  selector:
    app: gateway-api
    name: gateway-api
