<?php

return [
    '111 Sail',
    '1946 Nshd',
    '1950s',
    '5-fluoruracil',
    'A-fib',
    'A&e',
    'A&e Department',
    'A&e Waiting Time',
    'Abdominal',
    'Abdominal Mri',
    'Abdominal Pain',
    'Aberdeen',
    'Aberdeen Birth Cohorts',
    'Aberdeen Children',
    'Aberdeenshire',
    'Abvd',
    'Accelerometer',
    'Accelerometers',
    'Access',
    'Accident',
    'Accident & Emergency',
    'Accident And Emergency',
    'Accredited Social Health Activists',
    'Ace Inhibitors',
    'Acidosis',
    'Aconf',
    'Acs',
    'Active',
    'Activity Trackers',
    'Acuity',
    'Acuity Score',
    'Acute',
    'Acute Care',
    'Acute Care Process',
    'Acute Compartment Syndrome',
    'Acute Coronary Syndromes',
    'Acute Glaucoma',
    'Acute Hospitals',
    'Acute Illness',
    'Acute Ischemic Heart Diseases',
    'Acute Kidney Injury',
    'Acute Medical Care',
    'Acute Medical Unit',
    'Acute Medicine',
    'Acute Myocardial Infarction',
    'Acute Organisational Survey',
    'Acute Pld',
    'Acute Rheumatic Fever',
    'Acute Urethral Syndrome',
    'Adbe',
    'Addd',
    'Adde',
    'Administration',
    'Admire',
    'Admission',
    'Admission Diagnosis',
    'Admissions',
    'Admitted',
    'Admitted Patient Care',
    'Adolescence',
    'Adolescent',
    'Adult',
    'Adult Asthma',
    'Adult Brain Tumour',
    'Adult Social Care',
    'Adult Social Care Outcomes Framework',
    'Adults',
    'Advanced Cancer',
    'Affymetrix',
    'Aflibercept',
    'Age',
    'Age Related Macular Degeneration',
    'Age-related Macular Degeneration',
    'Ageing',
    'Ai',
    'Air Pollution',
    'Air Quality',
    'Airflow Limitation',
    'Airwave',
    'Airway Pressure',
    'Aki',
    'Alert',
    'Algorithm',
    'Allergy',
    'Alleviate',
    'Alpha Agonists',
    'Alpha Glucosidase Inhibitors',
    'Alpha2-adrenergic Agonists',
    'Alspac',
    'Alteplase',
    'Alzheimer\'s Disease',
    'Alzheimer\'s Disease (Disorder)',
    'Amblyopia',
    'Ambulance',
    'Ambulatory Emergency Care',
    'Amd',
    'Amm',
    'Amputation',
    'Amu',
    'Anaesthesia',
    'Anaesthetic',
    'Analgesia',
    'Anaplastic',
    'And Evaluation - Immunologic Surveillance - Sentinel Surveillance - Primary Health Care - Medical Record Linkage',
    'Aneurysm',
    'Angina',
    'Angina Pectoris',
    'Angioplasty',
    'Angiosarcoma',
    'Angle',
    'Ankle',
    'Antenatal',
    'Anterior Chamber',
    'Anthropometry',
    'Anti-cancer',
    'Anti-cancer Therapy',
    'Anti-coagulants',
    'Anti-pd-l1 Trial',
    'Antibiotic Prescribing',
    'Antibiotic Stewardship',
    'Antibiotic Therapy',
    'Antibiotics',
    'Antibodies',
    'Antibody',
    'Anticoagulants',
    'Anticoagulation',
    'Antigen',
    'Antimetabolite',
    'Antimicrobial Stewardship',
    'Antimicrobial Treatments',
    'Antioxidant Supplementation',
    'Antiphospholipid Syndrome (Disorder)',
    'Antiplatelet',
    'Antivirals',
    'Anxiety',
    'Aortic',
    'Apc',
    'Aphakic',
    'Appointment',
    'Appointment Keeping',
    'Appt',
    'Aps',
    'Archive',
    'Arctic',
    'Arden',
    'Ards',
    'Area Level',
    'Argon Laser Trabeculoplasty',
    'Arrhythmia',
    'Arrhythmias',
    'Arrival Method',
    'Arterial',
    'Arterial Blood Gas',
    'Arterioles And Capillaries',
    'Arthiritis',
    'Arthritis',
    'Artificial Intelligence',
    'Ascof',
    'Ash',
    'Asha',
    'Asia',
    'Asian',
    'Aspirin',
    'Asps',
    'Assuring Transformation',
    'Asthma',
    'Asthma (Disorder)',
    'Asthma Control',
    'Asthma Management',
    'Astigmatism',
    'Asymptomatic',
    'At',
    'Atrial Fibrillation',
    'Atrial Fibrillation And Flutter',
    'Atrial Fibrillation And Flutter (Disorder)',
    'Atrial Fibrilliation',
    'Attainment',
    'Attendance',
    'Attendance Type',
    'Auckar',
    'Audit',
    'Autoimmune',
    'Autoimmune Disease',
    'Automated Counter',
    'Automatic',
    'Avastin',
    'Avds',
    'Avoid Admissions',
    'Avon Longitudinal Study Of Parents And Children',
    'Avpu',
    'Axis',
    'Babies',
    'Baby',
    'Background',
    'Background Diabetic Retinopathy',
    'Bacteraemia',
    'Bacteria',
    'Bacterial',
    'Bacterial Infection',
    'Bacteriuria',
    'Bame',
    'Bangladesh',
    'Bangladeshi',
    'Bank',
    'Barrett\'s Oesophagus (Disorder)',
    'Barts',
    'Bartshealth',
    'Bcpap',
    'Bcs70',
    'Benign',
    'Benign Tumour Of Breast',
    'Best Corrected',
    'Beta Blockers',
    'Beta-blockers',
    'Betat-adrenergic Receptors Antagonists',
    'Bhf',
    'Bhf Data Science Centre',
    'Bhf Dsc',
    'Bib',
    'Bilateral',
    'Bio-repository',
    'Bio-sample',
    'Biobank',
    'Biochemical Measures',
    'Biochemistry',
    'Biodock',
    'Biological Parameters',
    'Biological Therapies',
    'Biology',
    'Biomarker Research',
    'Biomarkers',
    'Biomaterials',
    'Biomedical',
    'Biopsy',
    'Biorepository',
    'Birmingham',
    'Birth',
    'Births',
    'Black Carbon',
    'Bladder Cancer',
    'Bleed',
    'Bleeding',
    'Blood',
    'Blood Biomarkers',
    'Blood Cell',
    'Blood Clots',
    'Blood Glucose',
    'Blood Pressure',
    'Blood Results',
    'Blood Samples',
    'Blood Tests',
    'Blood Volume',
    'Blood-poisoning',
    'Bloods',
    'Bloodwise',
    'Bmi',
    'Bone Sarcoma',
    'Born In Bradford',
    'Bowel',
    'Bpd',
    'Brain',
    'Brain Mri',
    'Brain Tissue Bank',
    'Brain Tumour',
    'Brazil',
    'Brca1/brca2/hrd',
    'Breast',
    'Breast Cancer',
    'Breast Screening',
    'Breathe',
    'Breathe India',
    'Breathing',
    'Breathlessness',
    'Brecon',
    'Brian',
    'Bristol',
    'Bristol Dental School Saliva Bank',
    'Bubble Continuous Positive Airway Pressure',
    'Burden',
    'Business',
    'Bypass',
    'C-kit',
    'C-reactive Proteins',
    'Ca125',
    'Cafe',
    'Cafw',
    'Calcium Channel Blockers',
    'Caliber',
    'Cam-uroonc Biorepository',
    'Cambridge Blood And Stem Cell Biobank',
    'Camhs',
    'Cancellation',
    'Cancer',
    'Cancer Alliance',
    'Cancer Anniversary',
    'Cancer Bank',
    'Cancer Behaviour',
    'Cancer Of Unknown Primary',
    'Cancer Outcomes',
    'Cancer Registration',
    'Cancer Registry',
    'Cancer Research Uk',
    'Cancer Site',
    'Cancer Survivor',
    'Cancer Treatment',
    'Cancer Type',
    'Cancer Type, Cancer Behaviour, Cancer Anniversary, Cancer Site, Cancer Registra',
    'Cancer-related Stroke',
    'Cap',
    'Capd',
    'Carbonic Anhydrase Inhibitors',
    'Carcinoma',
    'Carcinoma In Situ Of Bladder',
    'Carcinoma In Situ Of Breast',
    'Carcinoma In Situ Of Liver',
    'Carcinoma In Situ Of Lung',
    'Carcinoma In Situ Of Pancreas',
    'Carcinoma In Situ Of Prostate',
    'Cardamon',
    'Cardiac',
    'Cardiac Mri',
    'Cardiff',
    'Cardiff University',
    'Cardioembolic',
    'Cardiomyopathy',
    'Cardiopulmonary Exercise Test',
    'Cardiorespiratory Health',
    'Cardiovascular',
    'Cardiovascular Disease',
    'Cardiovascular Magnetic Imaging',
    'Cardiovascular Mortality',
    'Cardioversion',
    'Care',
    'Care Escalation',
    'Care Home',
    'Care Packages',
    'Care Pathways',
    'Care Worker',
    'Care-seeking',
    'Careers Wales',
    'Caregivers',
    'Carer Experience',
    'Carers',
    'Carotid',
    'Carotid Ultrasound',
    'Carpal Tunnel Syndrome',
    'Cars',
    'Carw',
    'Case Management',
    'Case Note',
    'Case Note Review',
    'Case Study',
    'Casenote',
    'Casps',
    'Cat',
    'Cataract',
    'Cataracts',
    'Cause',
    'Cause Of Death',
    'Cbt',
    'Ccds',
    'Cclg',
    'Cdds',
    'Cds',
    'Cediranib',
    'Cehrb',
    'Cell',
    'Cellulitis',
    'Census',
    'Central Corneal Thickness',
    'Central England',
    'Central Nervous System',
    'Centre For Longitudinal Studies',
    'Cenw',
    'Cerebrovascular Accident',
    'Cerebrovascular Disease',
    'Cerebrovascular Disease (Disorder)',
    'Cerebrovascular Diseases',
    'Cerebrovascular Event',
    'Cervical',
    'Chemocare',
    'Chemotherapy/sact',
    'Chess',
    'Chest',
    'Chest Ct Scan',
    'Chest Mri',
    'Chest Pain',
    'Chest Radiographs',
    'Chest X-ray',
    'Chest X-rays',
    'Child',
    'Child And Adolescent Mental Health Services',
    'Child Health',
    'Childbirth',
    'Childhood',
    'Childhood Solid Tumours',
    'Childre',
    'Children',
    'Children & Young People',
    'Children And Young People',
    'Children And Young People Improving Access To Psychological Therapies',
    'Children And Young People Health Services Data Set',
    'Children With Asthma',
    'Children\'s Cancer',
    'Chill',
    'Cholecystectomy',
    'Chop-or',
    'Choroidal Neovascular Membrane',
    'Choroidal Neovascularization',
    'Chronic',
    'Chronic Bronchitis',
    'Chronic Care Patients',
    'Chronic Coronary Syndromes',
    'Chronic Fatigue Syndrome',
    'Chronic Glaucoma',
    'Chronic Ischemic Heart Disease',
    'Chronic Kidney Disease (Disorder)',
    'Chronic Liver Disease',
    'Chronic Multifocal Osteomyelitis (Disorder)',
    'Chronic Obstructive Pulmonary Disease',
    'Chronic Respiratory Disease',
    'Chronic Rheumatic Heart Diseases',
    'Chw',
    'Cidacs',
    'Cids',
    'Cinw',
    'Circulation',
    'Cirrhosis',
    'Cirrhosis Of Liver (Disorder)',
    'Ckd',
    'Classic',
    'Clear',
    'Climate & Sustainability',
    'Clinical',
    'Clinical Audit Dataset',
    'Clinical Dataset',
    'Clinical Disorder)',
    'Clinical Efficiency',
    'Clinical Events',
    'Clinical Frailty Scale',
    'Clinical Outcome',
    'Clinical Speciality',
    'Clinical Trial',
    'Clinical Trials',
    'Clinically Significant Macular Oedema',
    'Cll',
    'Cll210',
    'Clock Start',
    'Clock Stop',
    'Clots',
    'Clotting',
    'Cls',
    'Cmc',
    'Cnis',
    'Co Morbidity',
    'Co-cin',
    'Co-connect',
    'Co-morbidities',
    'Co-morbidity',
    'Co-stars',
    'Cog-uk',
    'Cognitive',
    'Cognitive Development',
    'Cognitive Measures',
    'Cohort',
    'Cohort Discovery',
    'Cohort Study',
    'Cohorts',
    'Colitis',
    'Collection',
    'Collections',
    'Colon',
    'Colorectal',
    'Colorectal Cancer',
    'Colour Photo',
    'Commissioning Data Sets',
    'Communication',
    'Community',
    'Community Acquired Pneumonia',
    'Community Health Worker',
    'Community Information Data Set',
    'Community Preception',
    'Community Providers',
    'Community Services',
    'Community Services Data Set',
    'Community Services, Csds, Digitrials',
    'Community Setting',
    'Comorbidity',
    'Complete Trisomy 21 Syndrome',
    'Complete Trisomy 21 Syndrome (Disorder)',
    'Computated Tomography Scan',
    'Computational Framework',
    'Computer Tomography',
    'Computerised Point Of Entry System',
    'Computerized - Biomedical Ontologies',
    'Computerized Axial Tomography',
    'Computor Tomography',
    'Cone Beam Computed Tomography',
    'Congenital',
    'Congenital Anomaly',
    'Congenital Anomaly Of Brain (Disorder)',
    'Congenital Brain Anomaly',
    'Congenital Glaucoma',
    'Consent',
    'Consolidation',
    'Contact Tracing',
    'Contacts',
    'Contextual Data',
    'Coordinate My Care',
    'Copd',
    'Copd Exacerbations',
    'Copdmap',
    'Copi',
    'Core',
    'Core-res',
    'Coricosteroids',
    'Cornea',
    'Coronary',
    'Coronary Artery Disease',
    'Coronary Syndrome',
    'Coronavirus',
    'Coronovirus',
    'Corticosteriods',
    'Corticosteroids',
    'Cosmic',
    'Cost',
    'Cost Effective',
    'Counselling',
    'Counts',
    'Covid',
    'Covid-19',
    'Covid-19 Hospitalisation In England Surveillance System',
    'Covid-19 Hospitalisation In England Surveillance System, Treatment, Outcome, Ri',
    'Covid-impact',
    'Covidsortium',
    'Cox\'s Bazar',
    'Cpap',
    'Cpes',
    'Cpoe',
    'Cprd Aurum',
    'Cprd Gold',
    'Crcs',
    'Creatine Kinase',
    'Crf',
    'Crime & Justice',
    'Cris',
    'Critical Care',
    'Critical Care Period',
    'Critical Care Records',
    'Critical Illness',
    'Crohn\'s',
    'Crohn\'s Disease',
    'Cross-linkage',
    'Crp',
    'Crp Inhibition',
    'Csds',
    'Ct Scan',
    'Cttp',
    'Ctu',
    'Culture Samples',
    'Cultures',
    'Curb Score',
    'Curb-65',
    'Custom',
    'Cvd',
    'Cvd-covid-uk',
    'Cvlf',
    'Cvsd',
    'Cvsp',
    'Cvst',
    'Cvvd',
    'Cyclodiode',
    'Cyfi',
    'Cylinder',
    'Cyp-iapt',
    'Cystic Fibrosis',
    'Cystitis',
    'Cystoid Macular Oedema',
    'D-dimer',
    'Daily',
    'Daily Records',
    'Daisy Tumour Bank',
    'Darwin1',
    'Dash',
    'Data',
    'Data Drive Model',
    'Data Science',
    'Data-can',
    'Database',
    'Dataloch',
    'Datamind',
    'Dataset',
    'Date',
    'Datw',
    'Day Case',
    'Day Cases',
    'Daycases',
    'Death',
    'Death Register',
    'Death Registration',
    'Deaths',
    'Deceased',
    'Decile',
    'Decision Support',
    'Decovid',
    'Deep Learning',
    'Defibrillator',
    'Degenerations',
    'Degenerative Brain Disorder',
    'Degenerative Brain Disorder (Disorder)',
    'Degenerative Disorder Of Macula (Disorder)',
    'Degrees',
    'Dehydrated',
    'Delivery Outcome',
    'Delivery Type',
    'Dementia',
    'Dementia (Disorder)',
    'Demographics',
    'Demography',
    'Dental',
    'Dental Caries (Disorder)',
    'Dentistry',
    'Dentists',
    'Depression',
    'Depression, Anxiety, Cbt, Counselling, Talking Therapy, Cognitive, National Cor',
    'Depressive Disorder (Disorder)',
    'Deprivation',
    'Desw',
    'Detection',
    'Deterioration',
    'Development',
    'Developmental',
    'Device',
    'Dexamethasone',
    'Diabetes',
    'Diabetes Inhibitors',
    'Diabetes Mellitus Type 1',
    'Diabetes Mellitus Type 2',
    'Diabetic Angiopathy',
    'Diabetic Coma',
    'Diabetic Eye Disease',
    'Diabetic Ketoacidosis',
    'Diabetic Kidney Disease',
    'Diabetic Macular Oedema',
    'Diabetic Maculopathy',
    'Diabetic Neuropathy',
    'Diabetic Retinopathy',
    'Diabetic Ulcer',
    'Diagnoses',
    'Diagnosis',
    'Diagnostic',
    'Diagnostic Delay',
    'Diagnostic Image',
    'Diagnostic Ultrasonography',
    'Diagnostics',
    'Dialysis',
    'Did Not Attend',
    'Dids',
    'Diet',
    'Digestive Diseases',
    'Digestive Health',
    'Digital Auscultation',
    'Digital Retinal Photography',
    'Digital Surveillance',
    'Digitrials',
    'Digitrials, A&e, Accident And Emergency, Ecds, Ncs, National Core Study, Urgent',
    'Digitrials, Gdppr, Ncs, Gp Data',
    'Digitrials, Pillar 2, Key Worker, Scotland, England, Wales, Northern Ireland, N',
    'Digitrials, Pillar 3, Scotland, England, Northern Ireland, Wales, Ncs, National',
    'Digitrials, Prescribing, Medicines, Dispensing, Ncs, National Core Study, Covid',
    'Digitrials, Sgss, Pillar 1, Ncs, Pillar 2, Pillar 3, England, National Core Stu',
    'Digitrials, Sus, Ncs, Sus+, Pbr, National Tariff, Cds, Commissioning Data Sets,',
    'Digitrials, Vaccination, England, National Core Study, Covid-19, Ncs',
    'Digitrials. England, National Core Study, Covid-19, Ncs',
    'Digoxin',
    'Diode Laser Cycloablation',
    'Dioptres',
    'Dipstick',
    'Disabilities',
    'Discharge',
    'Disciform Scar',
    'Discover',
    'Discover-now',
    'Disease',
    'Diseases Of Arteries',
    'Diseases Of The Circulatory System',
    'Disorder Of Digestive System (Disorder)',
    'Dispensing',
    'Dme',
    'Dmo',
    'Dna',
    'Dnr Status',
    'Do Not Resuscitate Orders',
    'Do Not Resusictate Orders',
    'Dose',
    'Dpp-4 Inhibitors',
    'Dr',
    'Drooling',
    'Drops',
    'Drug Administrations',
    'Drug History',
    'Drugdev',
    'Drugs',
    'Drusen',
    'Dry',
    'Dry Amd',
    'Dry Eye',
    'Dsrd',
    'Dundee',
    'Dundee And Aberdeen',
    'Dxa',
    'Dysarthria',
    'Dysphagia',
    'Dystrophies',
    'E-alerts',
    'Early',
    'Early Life Data',
    'Ecds',
    'Ecg',
    'Echo',
    'Economic Activity',
    'Ecoss',
    'Ed',
    'Edad',
    'Eddd',
    'Edds',
    'Edinburgh',
    'Edinburgh Cancer Centre',
    'Edinburgh Cancer Informatics',
    'Education',
    'Educational Intervention',
    'Eduw',
    'Ehr',
    'Elbow',
    'Elder Care',
    'Elderly',
    'Elective',
    'Elective Recovery',
    'Elective Services',
    'Electronic',
    'Electronic Health Record',
    'Electronic Health Records',
    'Electronic Healthcare System',
    'Elisa',
    'Elixir',
    'Elsa',
    'Embolisms',
    'Emep4uk',
    'Emergency',
    'Emergency Admissions',
    'Emergency Care',
    'Emergency Department',
    'Emergency Departments',
    'Emergency Laparotomy',
    'Emergency Services',
    'Emphysema',
    'Employment',
    'End Of Life',
    'End-stage Kidney Disease',
    'Endarterectomy',
    'Endocarditis',
    'Endocrine',
    'Endometrial',
    'Endophthalmitis',
    'England',
    'England Deaths',
    'English Deaths',
    'English Longitudinal Study Of Ageing',
    'Enterprise',
    'Entire Embryo (Body Structure)',
    'Environment',
    'Environmental',
    'Epidemiological',
    'Epidemiology',
    'Epigenetics',
    'Epilepsy',
    'Epilepsy (Disorder)',
    'Epilepsy 12',
    'Episode',
    'Episodes',
    'Episodes, Hospital, Critical Care, Diagnosis, Emergency, Operations, Critical C',
    'Episodes, Hospital, Diagnosis, Emergency, Accident, Operations, A&amp;e, A&amp;',
    'Episodes, Hospital, Diagnosis, Inpatients, Emergency, Operations, Admission, Fi',
    'Eskd',
    'Espac-tplus',
    'Estimate',
    'Estrogen',
    'Esus',
    'Etdrs',
    'Ethical Tissue',
    'Ethiopia',
    'Ethnic Minorities',
    'Ethnicity',
    'Eufs',
    'Eufss',
    'Evaluation',
    'Exacerbation',
    'Exacerbations',
    'Exam',
    'Exceed',
    'Exercise',
    'Exercise Challenge Test',
    'Exeter',
    'Exome',
    'Exome Sequencing',
    'Experience',
    'External Cause',
    'Exudative Age-related Macular Degeneration',
    'Eye',
    'Eye Condition',
    'Eye Drop',
    'Eyes',
    'Eylea',
    'Facilities Survey 2019',
    'Facility',
    'Faco',
    'Faculty Of Medicine',
    'Fae',
    'Failure',
    'Fall',
    'Fallopian',
    'Falls',
    'Family Court',
    'Family History',
    'Family Man',
    'Farm',
    'Farmer',
    'Fasciotomy',
    'Fasta',
    'Fasting Blood Glucose',
    'Fatigue',
    'Fbc',
    'Fce',
    'Fdg-pet',
    'Feasibility',
    'Feasibility Study',
    'Federated',
    'Females',
    'Fenland',
    'Fertility',
    'Fffap',
    'Ffpe',
    'Fibrosis',
    'Fife',
    'Finished Admission Episode',
    'Finished Consultant Episode',
    'Fit And Well',
    'Fit And Well Glioma (Disorder)meningitis (Disorder)',
    'Fit Test',
    'Fitness Trackers',
    'Flair',
    'Fluids',
    'Fluoroscopy',
    'Fman',
    'Foetal Tissue',
    'Foetus',
    'Follow-up',
    'Follow-up Health Status',
    'Foot',
    'Forecast',
    'Fracture',
    'Fracture Liaison Service',
    'Fragility',
    'Frail',
    'Frailty',
    'Frailty Index',
    'Fuchs Heterochromic Iridocyclitis',
    'Fundus',
    'Fundus Fluorescence Angiography',
    'Fundus Photograph',
    'Fundus Photographs',
    'Fungal',
    'Gall Bladder',
    'Gargling',
    'Gasp',
    'Gcp',
    'Gdppr',
    'Gel',
    'Gem-r-cvp',
    'General Medical Practitioners',
    'General Practice',
    'Generation',
    'Generation Scotland',
    'Genetic',
    'Genetic Testing',
    'Genetic Variants',
    'Genetics',
    'Genome',
    'Genomics',
    'Genotype',
    'Genpc',
    'Geographic Atrophy',
    'Geriatric Health',
    'Geriatrician',
    'Geriatrics',
    'Gestation',
    'Gestational Diabetes',
    'Giant Cell Arteritis (Disorder)',
    'Glad',
    'Glasgow',
    'Glaucoma',
    'Glaucoma Drainage Implants',
    'Gliptins',
    'Glitazones',
    'Global Health',
    'Glp-1',
    'Glp-1 Inhibitors',
    'Glp-1s',
    'Glucagon',
    'Glucose Intolerance',
    'Glycated Haemoglobin Test',
    'Goldman',
    'Gonioscopy',
    'Google',
    'Gosh',
    'Governance',
    'Gp',
    'Gp Data',
    'Gp Practice',
    'Gpcd',
    'Grade',
    'Grading',
    'Graduates',
    'Great Ormond Street Hospital',
    'Gro',
    'Growing Old',
    'Growing Up',
    'Growing Up In Bradford (Bib)',
    'Gwas',
    'Gynaecological Cancers',
    'Gynaecology',
    'Haemato-oncology',
    'Haematological Cancer',
    'Haematological Malignancies',
    'Haematology',
    'Haemodynamics',
    'Haemoglobin A1c',
    'Haemorrhage',
    'Haiti',
    'Hajj',
    'Hap',
    'Hapn',
    'Hat',
    'Hbrc',
    'Hcd',
    'Hcv',
    'Hcw',
    'Hdbr',
    'Hdr Uk',
    'Hdr Uk Phenotypes',
    'Hdu',
    'Head And Neck Cancers',
    'Headache',
    'Heaf',
    'Heal',
    'Health',
    'Health & Wellbeing',
    'Health Care Workers',
    'Health Conditions',
    'Health Data',
    'Health Facilities',
    'Health Journey',
    'Health Literacy',
    'Health Management Information System',
    'Health Service Utilisation',
    'Health Services',
    'Health Social Media',
    'Health Worker',
    'Healthboard',
    'Healthcare',
    'Healthcare Utilisation',
    'Healthcare Workers',
    'Healthy',
    'Heart',
    'Heart Attacks',
    'Heart Condition',
    'Heart Conditions',
    'Heart Disease',
    'Heart Failure',
    'Heart Rate',
    'Heidelberg',
    'Heidelberg Engineering',
    'Hematologic Neoplasm (Disorder)',
    'Hemiplegia',
    'Hepatic Venous Pressure Gradient',
    'Hepatitis C',
    'Hepato-pancreato Biliary',
    'Hepatobiliary',
    'Hepatopancreatobiliary Tumours',
    'Heritability',
    'Hes',
    'Hic',
    'High Blood Pressure',
    'High Cost Drugs',
    'High Dependency',
    'High Dependency Unit',
    'High Flow Nasal Oxygen',
    'High Flow Oxygen',
    'Higher Education',
    'Hip',
    'Hip Fracture',
    'Hiv',
    'Hnscc',
    'Hodgkin Lymphoma',
    'Hodgkin\'s Disease',
    'Hormonal Contraception',
    'Hormone Therapy',
    'Hospices',
    'Hospital',
    'Hospital Acquired Pneumonia',
    'Hospital Activity',
    'Hospital Admissions',
    'Hospital Episode Statistics',
    'Hospital Events',
    'Hospital Eye Service',
    'Hospital Inpatient Data',
    'Hospital Inpatient System',
    'Hospital Length Of Stay',
    'Hospital Outcomes',
    'Hospital Ward',
    'Hospitalisation',
    'Hospitalised',
    'Hospitalised Patients',
    'Household',
    'Housing & Communities',
    'Hpb',
    'Hpv',
    'Hqip',
    'Hsc',
    'Hta',
    'Human',
    'Human Activity Recognition',
    'Human Immunodeficiency Virus (Organism)',
    'Human Papillomavirus',
    'Humphrey',
    'Huntington\'s Chorea (Disorder)',
    'Hvpg',
    'Hwra',
    'Hypercholesterolaemia',
    'Hypercholesterolemia',
    'Hyperemesis Gravidarum',
    'Hyperglycaemia',
    'Hyperlactaemia',
    'Hyperlipidemia',
    'Hyperosmolar Hyperglycaemic State',
    'Hyperosmolar Hyperglycaemic Status',
    'Hypertension',
    'Hypertensive Diseases',
    'Hypertrophic Cardiomyopathy Patients',
    'Hypoglycaemia',
    'Hypovolaemia',
    'Hypoxemia',
    'Ibd',
    'Iccd',
    'Icd-10',
    'Icd10 Codes',
    'Icnarc',
    'Icnc',
    'Icoda',
    'Icon9',
    'Ict',
    'Icu',
    'Iddo',
    'Idiopathic Interstitial Pneumonia',
    'Idiopathic Pulmonary Fibrosis',
    'Idris',
    'Igc',
    'Ild',
    'Illness',
    'Image',
    'Images',
    'Imaging',
    'Imci',
    'Immune System',
    'Immune-mediated Inflammatory Diseases',
    'Immune-modifying Drugs',
    'Immunisation',
    'Immunisations',
    'Immunity',
    'Immuno-suppressant',
    'Immunology',
    'Imperial',
    'Implementation Research',
    'Import High',
    'Imputation',
    'Inactive',
    'Inatt',
    'Inca',
    'Incidence',
    'Incretin Mimetics',
    'India',
    'Indian',
    'Indicators',
    'Individually Linked',
    'Induced',
    'Inequality & Social Inclusion',
    'Infant',
    'Infection',
    'Infectious Diseases',
    'Inflammatory',
    'Inflammatory Bowel Disease',
    'Influenza Virus (Organism)',
    'Information Provision',
    'Information Storage And Retrieval - Controlled Vocabulary - Epidemiologic Studies - Cohort Studies - Case-control Studies - Observational Study - Clinical Trial - Health Care Quality',
    'Infusions',
    'Initial Assessment',
    'Injection',
    'Injections',
    'Injustis',
    'Inpatient',
    'Inpatient Falls',
    'Inpatient Medication',
    'Inpatients',
    'Inr',
    'Inspiratory Pressure',
    'Institute Of Genetics And Cancer',
    'Institutional Deaths',
    'Insulin',
    'Insulin Resistance',
    'Integrated Care',
    'Integrated Care Record',
    'Integrated Management Of Childhood Illness',
    'Intelligence',
    'Intensive Care',
    'Intensive Care Admission',
    'Intensive Care Unit',
    'International',
    'Interpret',
    'Intervention',
    'Interventions',
    'Intra-compartmental Pressure',
    'Intramuscular',
    'Intraocular Lens',
    'Intraocular Pressure',
    'Intravenous',
    'Intravenous Fluids',
    'Intravitreal Anti-vegf Injections',
    'Intubation',
    'Invasive Disease',
    'Investigations',
    'Involvement',
    'Io-r-cvp',
    'Iol',
    'Iol Implant',
    'Ion',
    'Iop',
    'Ip',
    'Ipf',
    'Iridocorneal Endothelial Syndrome',
    'Isar',
    'Isaric',
    'Isaric 4c',
    'Ischaemia',
    'Ischaemic',
    'Ischemic Heart Disease',
    'Ischemic Heart Disease (Disorder)',
    'Ischemic Heart Diseases',
    'Isolate',
    'Itu',
    'Iv Fluids',
    'Ivt',
    'Jakob-creutzfeldt Disease (Disorder)',
    'Joint',
    'Jpeg',
    'Jpg',
    'Justice',
    'Key Worker',
    'Keyhole Surgery',
    'Kidney',
    'Kidney Disease',
    'Kidney Failure',
    'Kidney Replacement Therapy',
    'King\'s College London',
    'King\'s Health Partners',
    'Klang',
    'Knee',
    'Kpis',
    'Krt',
    'Laboratory',
    'Laboratory E-alerts',
    'Laboratory Results',
    'Laboratory Turnaround Time',
    'Labour',
    'Labs',
    'Lactate',
    'Lactate Levels',
    'Lacw',
    'Lam',
    'Lao',
    'Laparotomy',
    'Laser',
    'Late Doses',
    'Lateral Flow',
    'Laterality',
    'Lbc1921',
    'Lbc1936',
    'Lbih',
    'Lbrtb',
    'Lcc',
    'Ld',
    'Learning',
    'Learning Disabilities',
    'Leeds',
    'Leeds Breast Research Tissue Bank',
    'Leeds Dental Institute',
    'Left',
    'Left Bundle Branch Block',
    'Leicester',
    'Length Of Stay',
    'Lens',
    'Leukaemia',
    'Leukopenia',
    'Level 2 Critical Care Bed',
    'Level 3 Critical Care Bed',
    'Life-threatening',
    'Lifestyle',
    'Lighthouse',
    'Limb',
    'Lims',
    'Lineage',
    'Linkable',
    'Linked',
    'Linked Longitudina',
    'Linked Longitudinal',
    'Linked Longitundinal',
    'Linked Nhs Data',
    'Lipidomics',
    'Lipoprotein Deficiency',
    'Liver',
    'Liver Diseases',
    'Liver Fibrosis',
    'London',
    'Long Covid',
    'Long Term Medical Conditions',
    'Longitudinal',
    'Longitudinal Data',
    'Loss To Follow-up',
    'Lothian',
    'Low Tension',
    'Low Tension Glaucoma',
    'Low-income',
    'Lower',
    'Ltat',
    'Lucentis',
    'Lung',
    'Lung Cancer',
    'Lung Disease',
    'Lung Diseases',
    'Lung Function',
    'Lung Volume Reduction',
    'Luton',
    'Lymphangioleiomyomatosis',
    'Lymphocyte',
    'Lymphoid Tissue',
    'Mab',
    'Mace',
    'Machine Learning',
    'Macrovascular Compilations',
    'Macula',
    'Macular',
    'Magnetic Resonance Imaging',
    'Main Speciality',
    'Major Adverse Cardiac Events',
    'Major Injuries',
    'Malawi',
    'Malaysia',
    'Malaysia Culturally-tailored School-based Interventions',
    'Malignancy',
    'Malignant Adrenal Gland Tumour',
    'Malignant Brain Neoplasm',
    'Malignant Breast Tumour',
    'Malignant Cervix Tumour',
    'Malignant Colon Tumour',
    'Malignant Connective Tissue Neoplasm',
    'Malignant Endometrium Of Corpus Uteri Neoplasm',
    'Malignant Eye Melanoma',
    'Malignant Kidney Tumour',
    'Malignant Liver Neoplasm',
    'Malignant Lymphoma',
    'Malignant Lymphoma (Disorder)',
    'Malignant Melanoma Of Eye',
    'Malignant Melanoma Of Eye (Disorder)',
    'Malignant Neoplasm Of Brain',
    'Malignant Neoplasm Of Connective Tissue (Disorder)',
    'Malignant Neoplasm Of Endometrium Of Corpus Uteri',
    'Malignant Neoplasm Of Endometrium Of Corpus Uteri (Disorder)',
    'Malignant Neoplasm Of Endometrium Of Corpus Uteri )',
    'Malignant Neoplasm Of Liver',
    'Malignant Neoplasm Of Skin',
    'Malignant Neoplasm Of Upper Respiratory Tract (Disorder)',
    'Malignant Oral Cavity Tumour',
    'Malignant Prostate Tumour',
    'Malignant Skin Neoplasm',
    'Malignant Stomach Tumour',
    'Malignant Thyroid Gland Tumour',
    'Malignant Tumour Of Breast',
    'Malignant Tumour Of Cervix',
    'Malignant Tumour Of Colon',
    'Malignant Tumour Of Kidney (Disorder)',
    'Malignant Tumour Of Lung',
    'Malignant Tumour Of Oesophagus',
    'Malignant Tumour Of Ovary',
    'Malignant Tumour Of Pancreas',
    'Malignant Tumour Of Penis (Disorder)',
    'Malignant Tumour Of Prostate (Disorder)',
    'Malignant Tumour Of Rectum (Disorder)',
    'Malignant Tumour Of Thyroid Gland (Disorder)',
    'Malignant Tumour Of Urinary Bladder (Disorder)',
    'Malignant Upper Respiratory Tract Neoplasm',
    'Malignant Urinary Bladder Tumour',
    'Mammography',
    'Management',
    'Manchester',
    'Maternal',
    'Maternal Deaths',
    'Maternity',
    'Maturity-onset Diabetes Of The Young (Disorder)',
    'Mcrc',
    'Mcs',
    'Mdsbio',
    'Me/cfs',
    'Mean Deviation',
    'Measures',
    'Mechanistic Target Of Rapamycin',
    'Medical Card',
    'Medical Imaging',
    'Medical Photography',
    'Medical Records Systems',
    'Medical Review',
    'Medical Students',
    'Medication',
    'Medication History',
    'Medications',
    'Medicine',
    'Medicines',
    'Medicines Reconciliation',
    'Meh',
    'Melanoma',
    'Mental Health',
    'Mental Health, Learning Disabilities, Child And Adolescent Mental Health Servic',
    'Meridian',
    'Mesobank',
    'Mesolthelioma',
    'Mesothelioma (Malignant',
    'Metabolic',
    'Metabolic Syndrome',
    'Metabolite',
    'Metabolomics',
    'Metabolon',
    'Metamorphopsia',
    'Metastatic',
    'Metastatic Disease',
    'Metformin',
    'Mexico',
    'Mft',
    'Mh',
    'Mhealth',
    'Mhldds',
    'Mhmds',
    'Mhsds',
    'Micro-health-centre',
    'Microaneurysm',
    'Microarray',
    'Microbiology',
    'Microbiology Samples',
    'Micropsia',
    'Microvascular Complications',
    'Microvasculature',
    'Middle-income',
    'Mids',
    'Millennium Cohort Study',
    'Million Women Study',
    'Minap',
    'Mineral Supplementation',
    'Minor Injuries',
    'Miotic Agents',
    'Miscarriage',
    'Missed Doses',
    'Misuse',
    'Mitomycin- C',
    'Mltcs',
    'Mnd',
    'Mni-corp',
    'Mobile App',
    'Mobility',
    'Modality',
    'Modelling',
    'Models',
    'Mof',
    'Molecular',
    'Monofocal',
    'Moorfields Eye Hospital',
    'Morbidity',
    'Mortality',
    'Mother',
    'Mother-baby',
    'Mother, Childbirth, Maternity, Births, Baby, Digitrials, Ncs, National Core Stu',
    'Motor Neuron Disease (Disorder)',
    'Mrc Hgu',
    'Mri',
    'Mtor',
    'Multi-morbidity',
    'Multidisciplinary Research',
    'Multimorbidity',
    'Multiomics',
    'Multiple Long Term Conditions',
    'Multiple Myeloma (Disorder)',
    'Multiple Sclerosis',
    'Multiple Sclerosis (Disorder)',
    'Multiple System Atrophy (Disorder)',
    'Musculoskeletal',
    'Mycocytes',
    'Myeloma Xii',
    'Myocardial',
    'Myocardial Infarction',
    'Nacap',
    'Nacel',
    'Nacrm',
    'Nacsa',
    'Nad',
    'Nafld',
    'Nap - Eip',
    'Nasal',
    'Nash',
    'National',
    'National Core Study',
    'National Diet',
    'National Early Warning Score',
    'National Interim Clinical Imaging Procedure Code Set',
    'National Neonatal Research Database',
    'National Organisational',
    'National Records Of Scotland',
    'National Screening Grading',
    'National Survey',
    'National Tariff',
    'Nausea',
    'Nboca',
    'Ncap',
    'Ncch',
    'Ncchd',
    'Nccid',
    'Ncds',
    'Nchda',
    'Ncras',
    'Ncs',
    'Nd:yag Laser Peripheral Iridotomy',
    'Ndns',
    'Nebuliser',
    'Nebulisers',
    'Neglect',
    'Neiaa',
    'Nela',
    'Neonatal',
    'Neonatal Care',
    'Neonatal Data Set',
    'Neonatal Deaths',
    'Neonatal Inpatient Stay',
    'Neoplasia',
    'Neoplasm',
    'Neovascular Age Related Macular Degeneration',
    'Neovascular Glaucoma',
    'Nepal',
    'Nephrotic Syndrome (Disorder)',
    'Ners',
    'Nerve Fibre Layer',
    'Nerves',
    'Neuroendocrine Tumours (Except Benign)',
    'Neurological',
    'Neurologist',
    'Neurology',
    'Neuropathology',
    'Neuropathy',
    'Neutrophil Counts',
    'Neutrophil Function',
    'New Vessels',
    'Newborn',
    'News2',
    'Next Steps',
    'Nhais',
    'Nhfa',
    'Nhs',
    'Nhs 111',
    'Nhs Digital',
    'Nhs Grampian',
    'Nhs Greater Glasgow & Clyde',
    'Nhs Scotland',
    'Nhs Scotland Outpatients',
    'Nhs24',
    'Nhsd',
    'Nhso',
    'Nib',
    'Nicam',
    'Nicip',
    'Nico',
    'Nicola',
    'Nicor',
    'Nicu',
    'Nihr',
    'Nihr Bioresource-coping',
    'Nihr Hic Acute Coronary Syndromes',
    'Nihr Hic Critical Care',
    'Nihr Hic Mental Health',
    'Nihr Hic Renal Transplantation',
    'Nihr Hic Viral Hepatitis',
    'Nilotinib',
    'Nimrad-trans',
    'Nims',
    'Niv',
    'Njr',
    'Nlp',
    'Nm',
    'Nmpa',
    'Nnap',
    'Nogca',
    'Non-invasive Ventilation',
    'Non-proliferative Diabetic Retinopathy',
    'Non-st Elevation',
    'Normal',
    'Normal Tension',
    'Normal Tension Glaucoma',
    'Northern Ireland',
    'Nosociomial Pneumonia',
    'Nottingham',
    'Npda',
    'Nrs',
    'Nstemi',
    'Nuclear Medicine',
    'Nursing Home',
    'Nurture',
    'Nutrition',
    'Nvr',
    'Obesity',
    'Observation',
    'Observational',
    'Observations',
    'Obstetrics',
    'Obstructive Lung Disease',
    'Occult',
    'Occupation',
    'Occupational Health',
    'Occupational Therapist',
    'Oct',
    'Oct Images',
    'Oct Nov 2019',
    'Octo',
    'Ocular',
    'Oesophago-gastric',
    'Office',
    'Offline Reinforcement Learning',
    'Olaparib',
    'Older Adults',
    'Older People',
    'Omb',
    'Omics',
    'Omop',
    'Oncology',
    'Online Health Communities',
    'Online Learning',
    'Ons',
    'Ooh',
    'Op',
    'Opcrd',
    'Opcs',
    'Opdw',
    'Open Data',
    'Open Pathways',
    'Operation',
    'Operational Efficiency',
    'Operations',
    'Ophthalmology',
    'Oprcd',
    'Oprd',
    'Optic',
    'Optic Disc',
    'Optic Nerve Head',
    'Optical Coherence Tomography',
    'Optical Coherence Tomography Angiography',
    'Optimising Pharmacology',
    'Oral',
    'Orbis',
    'Orbit',
    'Ordinary',
    'Organ Failure',
    'Organ Support',
    'Organisational',
    'Organisational Level',
    'Organisational Survey',
    'Orkney',
    'Orofacial Cleft (Disorder)',
    'Orthopaedic',
    'Osteoarthritis',
    'Osteomyelitus',
    'Osteoporosis',
    'Out Of Hours',
    'Outcome',
    'Outcomes',
    'Outcomes Medical Review',
    'Outliers',
    'Outpatient',
    'Outpatient Care',
    'Outpatient Care Data',
    'Outpatients',
    'Ovarian',
    'Ovary',
    'Overcrowding',
    'Oxford',
    'Oxford Healthcare Workers',
    'Oxygen',
    'Oxygen Levels',
    'Oxygen Saturations',
    'Oxygenation',
    'Pacemaker',
    'Pacemakers',
    'Pachymetry',
    'Pacs',
    'Paediatric',
    'Paediatric Sarcoma',
    'Pah',
    'Pain',
    'Pain Hub',
    'Pain Relief',
    'Pakistan',
    'Pakistani',
    'Palliative Care',
    'Palpitations',
    'Pam',
    'Pancreas',
    'Pandemic',
    'Pangolin',
    'Panther',
    'Paper Based Ordering',
    'Paper Systems',
    'Papers',
    'Parents',
    'Parkinson\'s',
    'Parkinson\'s Disease (Disorder)',
    'Parkinson\'s Specialist Nurse',
    'Parp Inhibitor',
    'Patd',
    'Path',
    'Pathology',
    'Pathway',
    'Pathways',
    'Patient',
    'Patient Activation',
    'Patient Administration System',
    'Patient Care And Outcomes',
    'Patient Experience',
    'Patient Index',
    'Patient Information',
    'Patient Level Data',
    'Patient Management',
    'Patient Outcomes',
    'Patient Pathways',
    'Patient Registration',
    'Patient Reported Experience Measures',
    'Patient Reported Outcomes',
    'Patient Safety',
    'Patient Survey',
    'Patients',
    'Pbmc',
    'Pbr',
    'Pci',
    'Pcp',
    'Peace',
    'Pediatric Care',
    'Pedw',
    'Peer',
    'Perceptions',
    'Percutaneous',
    'Percutaneous Coronary Intervention',
    'Performance',
    'Peri-operative Complications',
    'Peribulbar',
    'Perimetric Mean Deviation',
    'Perimetry',
    'Perinatal',
    'Peripheral Iridotomy',
    'Perscriptions',
    'Person Centred Care',
    'Personal',
    'Personalised Care',
    'Pet Scan',
    'Phacoemulsification',
    'Phacolytic Glaucoma',
    'Phacomorphic Glaucoma',
    'Phakic',
    'Pharmaceuticals',
    'Pharmacovigilance',
    'Pharmacy',
    'Pharmacy Interventions',
    'Phe',
    'Phenotype',
    'Phenotypes',
    'Phl',
    'Phoenix Ddr',
    'Photo',
    'Photograph',
    'Phs',
    'Physical Activity',
    'Physical Health',
    'Physical Measures',
    'Physical Parameters',
    'Physiology',
    'Physiology Readings',
    'Physiotherapist',
    'Physiotherapy',
    'Picanet',
    'Pictorial Asthma Action Plan',
    'Picture Archiving And Communication System',
    'Picu',
    'Pid',
    'Pigmentary Glaucoma',
    'Pilgrims',
    'Pillar 1',
    'Pillar 2',
    'Pillar 3',
    'Pinhole',
    'Pioneer',
    'Place Of Discharge',
    'Place Of Review',
    'Plain Radiography',
    'Planned',
    'Planned Behaviour',
    'Plant-based',
    'Plasma',
    'Plasmacytoma - Category (Morphologic Abnormality)',
    'Plasmamatch',
    'Platelet',
    'Platelets',
    'Platinum Resistance',
    'Pld',
    'Pneumonary',
    'Pneumonia',
    'Pneumonitis',
    'Police',
    'Policy',
    'Policy Research',
    'Political',
    'Pollen',
    'Pollution',
    'Polypharmacy',
    'Population',
    'Population Health Management',
    'Portal Hypertension',
    'Positron Emission Tomography',
    'Post Operative Complications',
    'Post-partum',
    'Postcode',
    'Posterior Capsular Rupture',
    'Posthumous',
    'Postnatal',
    'Postoperative',
    'Postponed',
    'Pout-t',
    'Pr',
    'Practice',
    'Practices',
    'Pragmatic Trial',
    'Prb',
    'Pre-diabetes',
    'Pre-excitation',
    'Pre-hospital',
    'Precision Medicine',
    'Prediction Model',
    'Predictive Values',
    'Prednisolone',
    'Pregnancy',
    'Pregnant Woman',
    'Prem',
    'Preoperative',
    'Preparedness',
    'Preprints',
    'Presbyopia',
    'Prescribing',
    'Prescriptions',
    'Presenting Complaints',
    'Preterm Birth',
    'Prevalence',
    'Prevelance',
    'Prevention',
    'Primary',
    'Primary Angle-closure',
    'Primary Angle-closure Glaucoma',
    'Primary Biliary Cholangitis',
    'Primary Care',
    'Primary Care Events',
    'Primary Care Physicians',
    'Primary Care Prescription',
    'Primary Care Prescriptions',
    'Primary Care Records',
    'Primary Education',
    'Primary Health',
    'Primary Health Care',
    'Primary Immunodeficiency',
    'Primary Open-angle',
    'Primary Open-angle Glaucoma',
    'Primary Peritoneal',
    'Primary Sjogren\'s Syndrome',
    'Prioritisation',
    'Private',
    'Probnp',
    'Procedure',
    'Procedure, Outpatients, Operations, Ncs, National Core Study, Main Specialty, H',
    'Procedures',
    'Professional',
    'Progesterone',
    'Prognosis',
    'Programme',
    'Progression/recurrence/survival',
    'Progressive Sclerosing Poliodystrophy (Disorder)',
    'Progressive Supranuclear Ophthalmoplegia (Disorder)',
    'Project-specific',
    'Projection',
    'Proliferative Diabetic Retinopathy',
    'Proms',
    'Prostaglandin Analogs',
    'Prostate',
    'Prostate Cancer',
    'Proteomics',
    'Prothrombin',
    'Protocol',
    'Pseudoexfoliative Glaucoma',
    'Pseudonymised',
    'Psp-ckd',
    'Psychiatric Inpatients',
    'Psychological',
    'Psychosis',
    'Psychotic Disorder (Disorder)',
    'Ptcl',
    'Public',
    'Public Health',
    'Public Health England',
    'Public Health Scotland',
    'Pulmonary Arterial Hypertension',
    'Pulmonary Embolus',
    'Pulmonary Heart Disease And Diseases Of Pulmonary Circulation',
    'Pulmonary Infiltrates',
    'Pulmonary Rehabilitation',
    'Pulse',
    'Pulse Oximetry',
    'Pulse Rate',
    'Pump',
    'Pune',
    'Pupil',
    'Pyelonephritis',
    'Qresearch',
    'Qualitative',
    'Quality',
    'Quality Improvement',
    'Quality Of Life',
    'Quality Outcomes',
    'Quality Survey',
    'Quantitative Trait Locus',
    'Quintile',
    'Radiogenomics',
    'Radiology',
    'Radiology Information System',
    'Radiotherapy',
    'Ranibizumab',
    'Rapamycin',
    'Rapid',
    'Rapid Decision Making',
    'Rapid Heart Rhythm',
    'Rapid Testing',
    'Rapper',
    'Rare Cancers',
    'Rare Disease',
    'Rare Diseases',
    'Rathl',
    'Rbac',
    'Rdetb',
    'Re-attendance',
    'Reablement',
    'Reach',
    'React',
    'React 1',
    'React 2',
    'React-1',
    'React-2',
    'Read Codes',
    'Read2',
    'Reading',
    'Readmissions',
    'Real World Data',
    'Real-world',
    'Recall',
    'Recipient Of Transplantation (Finding)',
    'Recovery',
    'Referral',
    'Referral To Treatment',
    'Refferal',
    'Refraction',
    'Register',
    'Registered Deaths',
    'Registration',
    'Registrations',
    'Registry',
    'Rehabilitation',
    'Reinfection',
    'Related Disease Outcomes',
    'Religion',
    'Remdesivir',
    'Remote',
    'Renal',
    'Renal Cancer',
    'Renal Disease',
    'Renal Replacement Therapy',
    'Repair',
    'Replacement',
    'Reported',
    'Repository',
    'Requite',
    'Research',
    'Research Centre',
    'Research Donors Ltd',
    'Resident Population',
    'Residential Care',
    'Resistance',
    'Resource Constrained',
    'Respiratory',
    'Respiratory Rate',
    'Respiratory Rate Counter',
    'Respiratory Tract',
    'Respire',
    'Results Of Ecg',
    'Retina',
    'Retinal',
    'Retinal Angiomatous Proliferation',
    'Retinal Detachment',
    'Retinal Photograph',
    'Retrospective Case Control Study',
    'Review',
    'Revised',
    'Rheumatology',
    'Rhythm',
    'Rialto',
    'Right',
    'Rio',
    'Ris',
    'Risk',
    'Risk Assessments',
    'Risk Modification',
    'Risk Prediction',
    'Risk Stratification',
    'Rna',
    'Role-based Access Control',
    'Routes',
    'Rpw',
    'Rpwd',
    'Rrt',
    'Rsv',
    'Rtb',
    'Rtds',
    'Rtt',
    'Rtt Pathway',
    'Rttd',
    'Rural',
    'Rural-urban',
    'Rwanda',
    'Sact',
    'Safe Haven',
    'Sail',
    'Salbutamol',
    'Saline',
    'Saliva',
    'Same Day Emergency Care',
    'Sample',
    'Sample Collection',
    'Samples',
    'Sarcoma',
    'Sars-cov-2',
    'Sars-cov2',
    'Sas',
    'Sbsw',
    'Sbtb',
    'Sbtw',
    'Scan',
    'Scan, Radiology, Diagnostic Image, X-ray, Plain Radiography, Cat,computerized A',
    'School',
    'School Of Dentistry',
    'School Workforce',
    'Schooling',
    'Scidiabetes',
    'Scot',
    'Scotland',
    'Scotland Births',
    'Scotland Stillbirths',
    'Scotoma',
    'Scottish',
    'Scottish Ambulance Service',
    'Scottish Cancer Registry',
    'Scottish Morbidity',
    'Scpm',
    'Screening',
    'Screening Programme',
    'Scsw',
    'Sdec',
    'Second-hand Smoke',
    'Secondary',
    'Secondary Angle-closure Glaucoma',
    'Secondary Care',
    'Secondary Care Organisational Dataset',
    'Secondary Care Records',
    'Secondary Care Workstream',
    'Secondary Glaucoma',
    'Secondary Infections',
    'Secondary Open-angle Glaucoma',
    'Selcoh',
    'Selective Laser Trabeculoplasty',
    'Self-management',
    'Self-protective',
    'Self-reported Data',
    'Sensitivities',
    'Sensorimotor Development',
    'Sentinel',
    'Sepsis',
    'Septicaemia',
    'Sequencing',
    'Sera',
    'Serial',
    'Serial Readings',
    'Series',
    'Sero-surveillance',
    'Seroepidemiology Unit',
    'Serology',
    'Seroprevelance',
    'Serum',
    'Ses',
    'Seu',
    'Severe',
    'Severity',
    'Sews',
    'Sex',
    'Sex Hormones.',
    'Sgss',
    'Share',
    'Sheffield',
    'Shetland',
    'Shielded',
    'Shoulder',
    'Sicsag',
    'Sight Impairment',
    'Sight Loss',
    'Simd',
    'Single Photon Emission Computerized Tomography',
    'Sinus Mode',
    'Siren',
    'Sitrep',
    'Sive',
    'Sjogren\'s Syndrome (Disorder)',
    'Skeletal',
    'Skeletal Tissues Bank',
    'Slam Pld',
    'Small Vessel Disease',
    'Smds',
    'Smoking',
    'Smoking Status',
    'Smr',
    'Smr00',
    'Smr01',
    'Smr02',
    'Smr04',
    'Smr06',
    'Snomed',
    'Snomed Ct',
    'Snomed-ct',
    'Snp',
    'Snp Chip',
    'Snps',
    'Social Care',
    'Social Deprivation',
    'Social Distancing',
    'Socio-economic Status',
    'Sociocultural Context',
    'Sociodemographics',
    'Socioeconomic',
    'Socioeconomic Data',
    'Socioeconomic Deprivation',
    'Socioeconomic Deprivations',
    'Socioeconomic Status',
    'Soft Tissue',
    'Solid Organ',
    'South Africa',
    'South Asian',
    'Southern Indian',
    'Specialist',
    'Specialty Care',
    'Spect',
    'Spectralis',
    'Speech And Language',
    'Spell',
    'Sphere',
    'Spike',
    'Spinal Muscular Atrophy (Disorder)',
    'Spirometa',
    'Spirometry',
    'Spontaneous',
    'Spotlight',
    'Sputum',
    'Ssnap',
    'St Thomas Hospitals',
    'Staff Grades',
    'Staff Questionnaire',
    'Stampede',
    'Standards',
    'Stemi',
    'Steroids',
    'Stillbirths',
    'Strabismus',
    'Stroke',
    'Stroke Unit',
    'Structured',
    'Students',
    'Study',
    'Sub-rpe Neovascularization',
    'Subarachnoid Intracranial Haemorrhage (Disorder)',
    'Subcutaneous',
    'Subretinal Fibrosis',
    'Subsequent St Elevation',
    'Substance',
    'Subtenons',
    'Sudan',
    'Sudden Cardiac Death',
    'Sulfonylurea',
    'Sulphonylurea',
    'Supported Self-management',
    'Surgeon',
    'Surgery',
    'Surgical Procedures',
    'Surveillance',
    'Survey',
    'Sus',
    'Sus+',
    'Swac',
    'Swallowing',
    'Swift-rtb',
    'Sylhet',
    'Symptom',
    'Symptomatic',
    'Symptoms',
    'Syndicate',
    'Synthetic',
    'Synthetic Data',
    'Systematic Anti-cancer Therapy',
    'Systematized Nomenclature Of Medicine Clinical Terms',
    'Tablets',
    'Talking Theraphy',
    'Tamil Nadu',
    'Tapb',
    'Tavi',
    'Tayside',
    'Teacher',
    'Tear',
    'Technology',
    'Teeth',
    'Teleconsultation',
    'Temperature',
    'Tertiary Care',
    'Test',
    'Testicular Cancer',
    'Testing',
    'The Airwave Health Monitoring Study',
    'The Brain Tumour Charity',
    'The Cleft Collective',
    'The Epic-norfolk Study',
    'Theatre',
    'Theory',
    'Therapies',
    'Therapist',
    'Therapy',
    'Thermofisher',
    'Threshold',
    'Thrombectomy',
    'Thrombolysis',
    'Thrombophlebitis',
    'Thrombosis',
    'Thrombotic',
    'Thrombus',
    'Thyroid',
    'Thyroid Cancers',
    'Tidal Volume',
    'Time In A&e',
    'Time Stamped',
    'Tissue',
    'Tissue Access For Patient Benefit',
    'Tissue Bank',
    'Tissue Solutions Ltd',
    'Tnt',
    'Tocilizumab',
    'Tommy\'s National Reproductive Health Biobank',
    'Tomosythesis',
    'Tonometry',
    'Tonopen',
    'Tonsillitis',
    'Tooth',
    'Topcon',
    'Topical',
    'Toric',
    'Toxicity',
    'Trabecular Meshwork',
    'Trabeculectomy',
    'Trace',
    'Trachiotomy',
    'Track-covid',
    'Tracker',
    'Training',
    'Trakcare',
    'Transfusions',
    'Transgenerational',
    'Transitional Cell Carcinoma',
    'Translational',
    'Translational Bladder Cancer',
    'Transmission',
    'Transmission Chains',
    'Transplant',
    'Transport',
    'Trauma',
    'Traumatic Glaucoma',
    'Traumatic Injury',
    'Tre',
    'Treatment',
    'Treatment Responses',
    'Treatment Speciality',
    'Treatments',
    'Trial',
    'Trials',
    'Trials, Studies, Nihr, Clinical Research, Icd10, Research Participation, Hrcs, Nhs Trust, Gp Practice, Nihr Crn',
    'Tricon8',
    'Tricon8b',
    'Triglycerides',
    'Triple Negative',
    'Troponin',
    'Troponins',
    'Trusted Research Environment',
    'Trusts',
    'Tumour',
    'Turbt',
    'Twin',
    'Twinsuk',
    'Type 1',
    'Type 2',
    'Type 2, Type 1, Insulin, Digitrials, Diabetes, Audit,',
    'Ucl',
    'Ucleb',
    'Uclh',
    'Uec',
    'Uganda',
    'Uhb',
    'Uk',
    'Uk Biobank',
    'Uk Llc',
    'Uk Longitudinal Linkage Collaboration',
    'Uk Renal Registry',
    'Ukall14',
    'Ukbileve',
    'Ukcrc Tissue Directory',
    'Ukctocs',
    'Ukhls',
    'Uklwc',
    'Ukrr',
    'Uktb',
    'Ultrasound',
    'Understanding Society',
    'Unicorn',
    'Unified',
    'Unirad',
    'University Of Bradford',
    'University Of Edinburgh',
    'University Of Liverpool',
    'University Of Oxford',
    'University Of Southampton',
    'Unplanned Investigation',
    'Unscheduled',
    'Unscheduled Care',
    'Upper Gastrointestinal (Gi) Tumours',
    'Urgent And Emergency Care',
    'Urgent Care',
    'Urinary Tract',
    'Urinary Tract Infection',
    'Urine',
    'Urine Culture',
    'Uropathogens',
    'Us',
    'Use Of Guidelines',
    'Uti',
    'Utuc',
    'Uveitic Glaucoma',
    'Va',
    'Vaccination',
    'Vaccine',
    'Varices',
    'Vascular',
    'Vascular Dementia (Disorder)',
    'Vegan',
    'Vegetarian',
    'Venous',
    'Ventilated',
    'Ventilation',
    'Ventilator Associated Pneumonia',
    'Verteporfin Photodynamic Therapy',
    'Video Expert',
    'Vincap',
    'Viral',
    'Viral Hepatitis Type C',
    'Viral Sequence',
    'Virology',
    'Vision',
    'Visual Acuity',
    'Visual Distortion',
    'Visual Field',
    'Vital Signs',
    'Vital-signs',
    'Vitamin D',
    'Vitamin K',
    'Vivaldi',
    'Vivaldi 2',
    'Vte',
    'Vulnerable Patient Groups',
    'Waiting List',
    'Waiting Times',
    'Wales',
    'Wales Deaths',
    'Wales Deaths, Welsh Deaths, Deaths, Gro, Deceased, English Deaths, Registered D',
    'Walker Study',
    'Wao',
    'Ward Admission',
    'Ward Transfers',
    'Wards',
    'Wasd',
    'Washing',
    'Wast',
    'Watch And Wait',
    'Wave 1',
    'Wave 2',
    'Wcb',
    'Wcisu',
    'Wcsu',
    'Wdds',
    'Wdsd',
    'Weakness',
    'Wearable Technology',
    'Weight',
    'Welsh',
    'Welsh Deaths',
    'Wes',
    'West Midlands',
    'Wet',
    'Wet Amd',
    'Wgs',
    'Wheeze',
    'White Cell Counts',
    'Whsd',
    'Wilms',
    'Wlgp',
    'Women\'s',
    'Women\'s Health',
    'Workflows',
    'Workforce',
    'Workload',
    'Workstream Resources',
    'World Of Work',
    'Wrrs',
    'X-ray',
    'York',
    'Yorkshire'
];
