<?php

return [
    'dataset' => [
        "Abdominal Aortic Aneurysm",
        "Abdominal Hernia",
        "Acarbose",
        "Ace Inhibitors",
        "Acei Loop Diuretic (M1)",
        "Acerbose",
        "Acne",
        "Actinic Keratosis",
        "Acute Kidney Injury",
        "Agranulocytosis",
        "Aids",
        "Alcohol",
        "Alcohol Consumption",
        "Alcohol Intake",
        "Alcohol Problems",
        "Alcoholic Liver Disease",
        "Allergic And Chronic Rhinitis",
        "Alopecia Areata",
        "Alpha Blockers",
        "Alpha-blockers",
        "Amiodarone (M2)",
        "Anal Fissure",
        "Anaphylaxis",
        "Angina",
        "Angiodysplasia Of Colon",
        "Angiotensin-iireceptorantagonists",
        "Ankylosing Spondylitis",
        "Anorectal Fistula",
        "Anorectal Prolapse",
        "Anorexia And Bulimia Nervosa",
        "Anterior And Intermediate Uveitis",
        "Anticoagulants",
        "Antidepressant",
        "Antidiabetic Medications",
        "Antiepileptic",
        "Antihypertensive Drugs",
        "Antiplatelet Agents",
        "Antiplatelets",
        "Antipsychotic",
        "Antipsychotics (P13)",
        "Anxiety",
        "Anxiety Disorder",
        "Anxiety Disorders",
        "Anxiolitics",
        "Anxiolytic Hypnotic",
        "Aplastic Anaemias",
        "Appendicitis",
        "Arrhythmia",
        "Asbestosis",
        "Aspiration Pneumonitis",
        "Aspirin (P3_p11)",
        "Asthma",
        "Asthma (P1)",
        "Asthma Clinicals",
        "Asthma Drugs",
        "Atrial Fibrillation",
        "Atrioventricular Block, Complete",
        "Atrioventricular Block, First Degree",
        "Atrioventricular Block, Second Degree",
        "Attention-deficit/hyperactivity Disorder (Adhd)",
        "Attention-deficit/hyperactivity Disorder (Adhd) Prod Codes",
        "Atypical Apds",
        "Autism And Asperger's Syndrome",
        "Autism Spectrum",
        "Autoimmune Liver Disease",
        "Back Pain",
        "Bacterial Diseases (Excl Tb)",
        "Bacterial Sepsis Of Newborn",
        "Barrett's Oesophagus",
        "Bell's Palsy",
        "Benign Neoplasm And Polyp Of Uterus",
        "Benign Neoplasm Of Brain And Other Parts Of Central Nervous System",
        "Benign Neoplasm Of Colon, Rectum, Anus And Anal Canal",
        "Benign Neoplasm Of Ovary",
        "Benign Neoplasm Of Stomach And Duodenum",
        "Benzodiazepines",
        "Beta Blockers",
        "Beta-blockers",
        "Betablockers (P1)",
        "Bifascicular Block",
        "Bipolar Affective Disorder And Mania",
        "Bipolar Disorder",
        "Bisphosphonates",
        "Blood Pressure",
        "Blood Pressure Measurement",
        "Blood Sugar",
        "Body Mass Index",
        "Body Mass Index (P17)",
        "Borderline Personality Disorder",
        "Breast Cancer",
        "Breast Cancer Gene (P19)",
        "Bronchiectasis",
        "Bronchiestasis",
        "Ca Channel Blocker",
        "Calcium Blockers",
        "Calcium Channel Blockers",
        "Cancer",
        "Cancer Immunotherapy Medication",
        "Carcinoma In Situ_cervical",
        "Cardiac Failure",
        "Cardiovascular Disease",
        "Cardiovascular Disease (Cvd) Risk Score",
        "Cardiovascular Disease (Psoriasis Association Study With Cvd)",
        "Cardiovascular Event",
        "Cardiovascular Events",
        "Carpal Tunnel Syndrome",
        "Case Definition For Alcohol Dependence",
        "Cataract",
        "Cerebral Palsy",
        "Charlson Comorbidity Index",
        "Chemotherapy Medication",
        "Cholangitis",
        "Cholecystitis",
        "Cholelithiasis",
        "Cholesterol Level",
        "Chronic Kidney Disease",
        "Chronic Kidney Disease (Ckd)",
        "Chronic Obstructive Pulmonary Disease",
        "Chronic Obstructive Pulmonary Disease (Copd)",
        "Chronic Pulmonary Disease",
        "Chronic Renal Disease",
        "Chronic Sinusitis",
        "Chronic Viral Hepatitis",
        "Clinically Significant Alcohol Misuse",
        "Clopidogrel (P3)",
        "Coeliac Disease",
        "Cold",
        "Collapsed Vertebra",
        "Colon Cancer",
        "Comorbidities",
        "Conduct Disorder",
        "Congenital Anomalies In Children",
        "Congenital Malformations Of Cardiac Septa",
        "Congestive Cardiac Failure",
        "Congestive Heart Disease",
        "Contrceptive",
        "Copd",
        "Coronary Artery Bypass Grafting",
        "Coronary Heart Disease",
        "Coronary Heart Disease (Chd)",
        "Coronary Heart Disease Not Otherwise Specified",
        "Coronary Revascularisation",
        "Covid-19 Infection",
        "Crohn's Disease",
        "Current Smoker (P18)",
        "Cystic Fibrosis",
        "Delirium, Not Induced By Alcohol And Other Psychoactive Substances",
        "Dementia",
        "Dementia (P13)",
        "Depot Apds",
        "Depression",
        "Dermatitis (Atopc/contact/other/unspecified)",
        "Diabetes",
        "Diabetes Medication",
        "Diabetes Mellitus",
        "Diabetes Mellitus Type Ii (Dmii)",
        "Diabetes Mellitus, Of Various Forms",
        "Diabetic Complications",
        "Diabetic Neurological Complications",
        "Diabetic Ophthalmic Complications",
        "Diaphragmatic Hernia",
        "Digoxin (P9)",
        "Dilated Cardiomyopathy",
        "Diseases Causing Hypoglycemia",
        "Disorders Of Autonomic Nervous System",
        "Diuretics",
        "Diuretics Thiazide",
        "Diverticular Disease Of Intestine (Acute And Chronic)",
        "Down's Syndrome",
        "Dpp-4inhibitors",
        "Dpp4",
        "Drugs",
        "Dysmenorrhoea",
        "Ear And Upper Respiratory Tract Infections",
        "Eating Disorder",
        "Ehnicity",
        "Encephalitis",
        "End Stage Renal Disease",
        "End-stage Renal Disease (Esrd)",
        "Endometrial Hyperplasia And Hypertrophy",
        "Endometriosis",
        "Enteropathic Arthropathy",
        "Enthesopathies & Synovial Disorders",
        "Eosinophils",
        "Epilepsy",
        "Epilepsy Clinicals",
        "Epilepsy Drugs",
        "Erectile Dysfunction",
        "Essential Tremor",
        "Ethnic Status",
        "Ethnicity",
        "Exercise Testing",
        "Extra Referral Codes",
        "Eye Infections",
        "Fatty Liver",
        "Female Genital Prolapse",
        "Female Infertility",
        "Female Pelvic Inflammatory Disease",
        "Fibromatoses",
        "Folate Deficiency Anaemia",
        "Fracture Of Hip",
        "Fracture Of Wrist",
        "Gastritis And Duodenitis",
        "Gastro-oesophageal Reflux Disease",
        "Gastroprotection",
        "Giant Cell Arteritis",
        "Glaucoma",
        "Glinide",
        "Glitazone (P5)",
        "Glomerulonephritis",
        "Glp-1receptoragonists",
        "Gout",
        "Gpl1",
        "Haemangioma, Any Site",
        "Hba1c Testing",
        "Hdl Cholesterol",
        "Hearing Loss",
        "Heart Failure",
        "Heart Failure (P5)",
        "Heart Rate",
        "Hemiplegia And Paraplegia",
        "Hepatic Failure",
        "Hidradenitis Suppurativa",
        "High Birth Weight",
        "Hiv",
        "Hodgkin Lymphoma",
        "Homelessness",
        "Hormone Replacement Drugs",
        "Hormone Replacement Therapy",
        "Hrt Oestrogens (P19)",
        "Hydrocoele (Incl Infected)",
        "Hyperkinetic Disorders",
        "Hyperparathyroidism",
        "Hyperplasia Of Prostate",
        "Hypertension",
        "Hypertension (Ht)",
        "Hypertrophic Cardiomyopathy",
        "Hypertrophy Of Nasal Turbinates",
        "Hypo Or Hyperthyroidism",
        "Hyposplenism",
        "Hypotension Drugs",
        "Hypothyroidism",
        "Illicit Opioid Use",
        "Immunodeficiencies",
        "Infection Of Anal And Rectal Regions",
        "Infection Of Bones And Joints",
        "Infection Of Liver",
        "Infection Of Male Genital System",
        "Infection Of Other Or Unspecified Genitourinary System",
        "Infection Of Skin And Subcutaneous Tissues",
        "Infections Of Other Or Unspecified Organs",
        "Infections Of The Digestive System",
        "Infections Of The Heart",
        "Inflammatory Bowel Disease",
        "Influenza Immunisation",
        "Influenza Immunisation Drugs",
        "Insulin",
        "Intellectual Disability",
        "International Normalized Ratio (M5)",
        "Intervertebral Disc Disorders",
        "Intracerebral Haemorrhage",
        "Intracranial Hypertension",
        "Intrauterine Hypoxia",
        "Iron Deficiency Anaemia",
        "Irritable Bowel Syndrome",
        "Ischaemia Heart Disease",
        "Ischaemic Heart Disease",
        "Ischaemic Stroke",
        "Juvenile Arthritis",
        "Juvenile Idiopathic Arthritis (Jia)",
        "Keratitis",
        "Labaics (P2)",
        "Ldl Cholesterol",
        "Learning Disability",
        "Left Bundle Branch Block",
        "Leiomyoma Of Uterus",
        "Leukaemia",
        "Lft Fbc (M3)",
        "Li Level (M4)",
        "Lichen Planus",
        "Lipid Lowering Agents",
        "Lipid Lowering Other",
        "Lithium",
        "Lithium (M4)",
        "Lithium And Other Mood Stabilisers",
        "Lithium Drug Codes",
        "Lithium Levels",
        "Lithium Therapy",
        "Liver Fibrosis, Sclerosis And Cirrhosis",
        "Loop Diuretics",
        "Low Hdl-c",
        "Lower Respiratory Tract Infections",
        "Lung Cancer",
        "Lupus Erythematosus (Local And Systemic)",
        "Lymphocytes",
        "Macrovascular Complications",
        "Macular Degeneration",
        "Male Infertility",
        "Marital Status",
        "Meglitinide",
        "Meniere Disease",
        "Meningitis",
        "Menorrhagia And Polymenorrhoea",
        "Metastatic Tumour",
        "Metformin",
        "Metformin (P8)",
        "Methicillin-resistant Staphylococcus Aureus (Mrsa)",
        "Methotrexate (M3)",
        "Micro-albuminuria Testing",
        "Microvascular Complications",
        "Migraine",
        "Mild Liver Disease",
        "Moderate Or Severe Liver Disease",
        "Monoclonal Gammopathy Of Undetermined Significance (Mgus)",
        "Motor Neuron Disease",
        "Multiple Myeloma And Malignant Plasma Cell Neoplasms",
        "Multiple Sclerosis",
        "Multiple Valve Dz",
        "Myasthenia Gravis",
        "Mycoses",
        "Myelodysplastic Syndromes",
        "Myocardial Infarction",
        "Nasal Polyp",
        "Neonatal Jaundice (Excl Haemolytic Dz Of The Newborn)",
        "Neuromuscular Dysfunction Of Bladder",
        "Neuropathic Pain",
        "Neuropathy",
        "Neutrophils",
        "Nitrates",
        "Non-acute Cystitis",
        "Non-covid19 Cvd Death",
        "Non-hodgkin Lymphoma",
        "Nonrheumatic Aortic Valve Disorders",
        "Nonrheumatic Mitral Valve Disorders",
        "Nsaid",
        "Obesity",
        "Obsessive-compulsive Disorder",
        "Obsessive-compulsive Disorder (Ocd)",
        "Obstructive And Reflux Uropathy",
        "Oesophageal Varices",
        "Oesophagitis And Oesophageal Ulcer",
        "Oesophagus Cancer",
        "Opioid",
        "Opioid Analgesics",
        "Oral Decongestants",
        "Osteoarthritis",
        "Osteoarthritis (Excl Spine)",
        "Osteoporosis",
        "Other Adds",
        "Other Anaemias",
        "Other Antihypertensives",
        "Other Cardiomyopathy",
        "Other Coronary Heart Disease",
        "Other Haemolytic Anaemias",
        "Other Interstitial Pulmonary Diseases With Fibrosis",
        "Other Nervous System Infections",
        "Other Or Unspecified Infectious Organisms",
        "Other Psychoactive Substance Misuse",
        "Otitis Media",
        "Ovarian Cancer",
        "Pancreas Cancer",
        "Pancreatitis",
        "Parasitic Infections",
        "Parkinson's Disease",
        "Patent Ductus Arteriosus",
        "Peptic (P3)",
        "Peptic Ulcer Disease",
        "Percutaneous Transluminal Coronary Angioplasty",
        "Pericardial Effusion (Noninflammatory)",
        "Peripheral Arterial Disease",
        "Peripheral Neuropathies (Excluding Cranial Nerve And Carpal Tunnel Syndromes)",
        "Peripheral Vascular Disease",
        "Peritonitis",
        "Personality Disorder",
        "Personality Disorders",
        "Physical Activity",
        "Pilonidal Cyst/sinus",
        "Pleural Effusion",
        "Pleural Plaque",
        "Pneumococcal Vaccin",
        "Pneumonia",
        "Pneumothorax",
        "Polycystic Ovarian Syndrome",
        "Polycythaemia Vera",
        "Polymyalgia Rheumatica",
        "Portal Hypertension",
        "Post-term Infant",
        "Postcoital And Contact Bleeding",
        "Posterior Uveitis",
        "Postinfective And Reactive Arthropathies",
        "Postmenopausal Bleeding",
        "Postviral Fatigue Syndrome, Neurasthenia And Fibromyalgia",
        "Pregnancy",
        "Prematurity",
        "Primary Malignancy_biliary Tract",
        "Primary Malignancy_bladder",
        "Primary Malignancy_bone And Articular Cartilage",
        "Primary Malignancy_brain, Other Cns And Intracranial",
        "Primary Malignancy_breast",
        "Primary Malignancy_cervical",
        "Primary Malignancy_colorectal And Anus",
        "Primary Malignancy_kidney And Ureter",
        "Primary Malignancy_liver",
        "Primary Malignancy_lung And Trachea",
        "Primary Malignancy_malignant Melanoma",
        "Primary Malignancy_mesothelioma",
        "Primary Malignancy_multiple Independent Sites",
        "Primary Malignancy_oesophageal",
        "Primary Malignancy_oro-pharyngeal",
        "Primary Malignancy_other Organs",
        "Primary Malignancy_other Skin And Subcutaneous Tissue",
        "Primary Malignancy_ovarian",
        "Primary Malignancy_pancreatic",
        "Primary Malignancy_prostate",
        "Primary Malignancy_stomach",
        "Primary Malignancy_testicular",
        "Primary Malignancy_thyroid",
        "Primary Malignancy_uterine",
        "Primary Or Idiopathic Thrombocytopaenia",
        "Primary Pulmonary Hypertension",
        "Prostate Cancer",
        "Protein Kinase Inhibitor Medication",
        "Proteinuria",
        "Psoriasis",
        "Psoriatic Arthritis",
        "Psoriatic Arthropathy",
        "Psychosis (P13)",
        "Psychosocial Support",
        "Ptosis Of Eyelid",
        "Pulmonary Collapse (Excl Pneumothorax)",
        "Pulmonary Embolism",
        "Raised Ldl-c",
        "Raised Total Cholesterol",
        "Raised Triglycerides",
        "Rasinhibitors",
        "Raynaud's Syndrome",
        "Renal Cancer",
        "Renal Disease",
        "Respiratory Distress Of Newborn",
        "Respiratory Failure",
        "Respiratory Tract Infection",
        "Retinal Detachments And Breaks",
        "Retinal Screening",
        "Retinal Vascular Occlusions",
        "Rheumatic Fever",
        "Rheumatic Valve Dz",
        "Rheumatoid Arthritis",
        "Rheumatoid Arthritis Group1",
        "Rheumatoid Arthritis Group2",
        "Rheumatoid Arthritis Group3",
        "Rheumatoid Arthritis Group4",
        "Rheumatological Disease",
        "Right Bundle Branch Block",
        "Rosacea",
        "Sarcoidosis",
        "Schizophrenia Spectrum",
        "Schizophrenia, Schizotypal And Delusional Disorders",
        "Scleritis And Episcleritis",
        "Scoliosis",
        "Screen Breast",
        "Screen Cervical",
        "Seborrheic Dermatitis",
        "Secondary Malignancy_adrenal Gland",
        "Secondary Malignancy_bone",
        "Secondary Malignancy_bowel",
        "Secondary Malignancy_brain, Other Cns And Intracranial",
        "Secondary Malignancy_liver And Intrahepatic Bile Duct",
        "Secondary Malignancy_lung",
        "Secondary Malignancy_lymph Nodes",
        "Secondary Malignancy_other Organs",
        "Secondary Malignancy_pleura",
        "Secondary Malignancy_retroperitoneum And Peritoneum",
        "Secondary Or Other Thrombocytopaenia",
        "Secondary Polycythaemia",
        "Secondary Pulmonary Hypertension",
        "Selective Serotonin Reuptake Inhibitor (Ssri) Adds",
        "Self Harm",
        "Septicaemia",
        "Serious Mental Illness (Smi)",
        "Serious Mental Illness (Smi) Drugs",
        "Serum Creatine",
        "Serum Creatine Testing",
        "Serum Creatinine Tests",
        "Sglt-2inhibitors",
        "Sick Sinus Syndrome",
        "Sickle-cell Anaemia",
        "Sickle-cell Trait",
        "Sjogren's Disease",
        "Sleep Apnoea",
        "Slow Fetal Growth Or Low Birth Weight",
        "Smoking",
        "Smoking Status",
        "Smoking Status (P18)",
        "Social Dysfunction",
        "Socioeconomic Deprevation",
        "Spina Bifida",
        "Spinal Stenosis",
        "Spirometry",
        "Splenectomy",
        "Splenomegaly",
        "Spondyloarthropathy",
        "Spondylolisthesis",
        "Spondylosis",
        "Stable Angina",
        "Statins",
        "Statins Plus Other Ll",
        "Stomach Cancer",
        "Stroke",
        "Stroke Nos",
        "Strong Analgesics",
        "Subarachnoid Haemorrhage",
        "Subdural Haematoma - Nontraumatic",
        "Substance Misuse",
        "Sulfonylureas",
        "Sulphonylureas",
        "Sumatriptan",
        "Supraventricular Tachycardia",
        "Syndrome Of Inappropriate Secretion Of Antidiuretic Hormone",
        "Synovitis",
        "Systemic Lupus Erthematosus",
        "Systemic Sclerosis",
        "Thalassaemia",
        "Thalassaemia Trait",
        "Thiazolidinediones",
        "Thrombophilia",
        "Thrombosis (P16)",
        "Thyroid Function",
        "Thyroid Function Test (M2)",
        "Tics",
        "Tinnitus",
        "Transient Ischaemic Attack",
        "Transplant",
        "Tricyclic Adds",
        "Trifascicular Block",
        "Trigeminal Neuralgia",
        "Tryglicerides",
        "Tuberculosis",
        "Tubulo-interstitial Nephritis",
        "Type 1 Diabetes",
        "Type 2 Diabetes",
        "Typical Apds",
        "Ulcerative Colitis",
        "Undescended Testicle",
        "Unnamed Inflammatory Arthritis",
        "Unstable Angina",
        "Upper Gastro Intestinal Malignancy",
        "Urea And Electrolytes (M1)",
        "Urinary Incontinence",
        "Urinary Tract Infections",
        "Urolithiasis",
        "Urticaria",
        "Venous Thromboembolic Disease (Excl Pe)",
        "Ventricular Tachycardia",
        "Viral Diseases (Excl Chronic Hepatitis/hiv)",
        "Visual Impairment And Blindness",
        "Vitamin B12 Deficiency Anaemia",
        "Vitiligo",
        "Volvulus",
        "Warfarin",
        "White Blood Cells"
    ],
];