name: Run quality checks
run-name: ${{ github.actor }} triggered quality check pipeline
on:
  push:
    branches:
      - dev
      - main
      - GAT-3817

  pull_request:
    branches:
      - main
      - dev
      - release

env:
  SLACK_WEBHOOK_URL: '${{ secrets.SLACK_WEBHOOK_URL}}'
  SLACK_CHANNEL: '${{ secrets.GITHUBACTIONS_SLACK_CHANNEL }}'

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Composer install
      run: "composer install"

    - name: Run static analysis
      run: "composer run phpstan"
  
    - name: Run unit tests
      run: "php artisan test"

    - name: Run code sniffer
      run: "composer run phpcs"

    - name: Run Notification
      id: runnotificationsent
      uses: act10ns/slack@v1
      with:
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: ${{ env.SLACK_CHANNEL }}
        message: Running automated tests on {{ env.GITHUB_REF_NAME }} branch failed
      if: always()