name: Release workflow
run-name: ${{ github.actor }} triggered Release workflow

on:
  push:
    branches:
      - "release/*"

jobs:
  release:
    uses: HDRUK/github-actions-templates/.github/workflows/docker-build.yaml@main
    with:
      gar_name: dta-web
      environments: '["preprod","prod"]'
      chart_path: chart/gateway-api/Chart.yaml
    secrets: inherit