name: Semantic Release workflow

on:
  push:
    branches:
      - main

jobs:
  semantic:
    uses: HDRUK/github-actions-templates/.github/workflows/semantic.yaml@main
    with:
      chart_path: chart/gateway-api/Chart.yaml
    secrets: inherit

  build:
    uses: HDRUK/github-actions-templates/.github/workflows/docker-build.yaml@main
    needs: semantic
    with:
      chart_path: chart/gateway-api/Chart.yaml
      environment: prod
    secrets: inherit
